/***************************
DateTime: 2023-01-26, 09:33:51
File list:
* jquery.ajaxchimp.min.js
* jquery.countTo.js
* jquery.easing.1.3.js
* jquery.localScroll.min.js
* jquery.downCount.js
* jquery.lazyload.min.js
* jquery.magnific-popup.min.js
* jquery.parallax-1.1.3.js
* jquery.scrollTo.min.js
* jquery.simple-text-rotator.min.js
* jquery.viewport.mini.js
* jquery.sticky.js
*****************************/
(function(b){b.ajaxChimp={responses:{"Thank you! You have subscribed successfully.":0,"Please enter a value":1,"An email address must contain a single @":2,"The domain portion of the email address is invalid (the portion after the @: )":3,"The username portion of the email address is invalid (the portion before the @: )":4,"This email address looks fake or invalid. Please enter a real email address":5},translations:{en:null},init:function(a,j){b(a).ajaxChimp(j)}};b.fn.ajaxChimp=function(a){return b(this).each(function(j,
f){var d=b(f),g=d.find("input[type=email]"),h=d.find("label[for="+g.attr("id")+"]"),k=b.extend({url:d.attr("action"),language:"en"},a),r=k.url.replace("/post?","/post-json?").concat("&c=?");d.attr("novalidate","true");g.attr("name","EMAIL");d.submit(function(){var n,p={},o=d.serializeArray();b.each(o,function(m,q){p[q.name]=q.value});b.ajax({url:r,data:p,success:function(m){if("success"===m.result){n=m.msg;h.removeClass("error").unwrap().wrap("<div class='success'></div>");g.removeClass("error").addClass("valid")}else{g.removeClass("valid").addClass("error");
h.removeClass("valid").unwrap().wrap("<div class='error'></div>");try{var q=m.msg.split(" - ",2);n=void 0!==q[1]&&parseInt(q[0],10).toString()===q[0]?q[1]:m.msg}catch(v){n=m.msg}}"en"!==k.language&&void 0!==b.ajaxChimp.responses[n]&&b.ajaxChimp.translations&&b.ajaxChimp.translations[k.language]&&b.ajaxChimp.translations[k.language][b.ajaxChimp.responses[n]]&&(n=b.ajaxChimp.translations[k.language][b.ajaxChimp.responses[n]]);h.html(n);h.show();k.callback&&k.callback(m)},dataType:"jsonp",error:function(m,
q){console.log("mailchimp ajax submit error: "+q)}});return"en"!==k.language&&b.ajaxChimp.translations&&b.ajaxChimp.translations[k.language]&&b.ajaxChimp.translations[k.language].submit&&(o=b.ajaxChimp.translations[k.language].submit),h.unwrap().wrap("<div class='success'></div>").html("Submitting...").show(),false})}),this}})(jQuery);(function(b){b("#mailchimp").find(".newsletter-field").first().attr("id","newsletter_field");b("#subscribe-result").html("<label for='newsletter_field'></label>");b("#mailchimp").ajaxChimp({url:"https://games.us6.list-manage.com/subscribe/post?u=7d6839817c6c926621240bbda&id=abb7d6b770&f_id=00510fe3f0"})})(jQuery);
(function(b){b.fn.countTo=function(a){a=a||{};return b(this).each(function(){function j(o){o=f.formatter.call(h,o,f);k.text(o)}var f=b.extend({},b.fn.countTo.defaults,{from:b(this).data("from"),to:b(this).data("to"),speed:b(this).data("speed"),refreshInterval:b(this).data("refresh-interval"),decimals:b(this).data("decimals")},a),d=Math.ceil(f.speed/f.refreshInterval),g=(f.to-f.from)/d,h=this,k=b(this),r=0,n=f.from,p=k.data("countTo")||{};k.data("countTo",p);p.interval&&clearInterval(p.interval);p.interval=
setInterval(function(){n+=g;r++;j(n);typeof f.onUpdate=="function"&&f.onUpdate.call(h,n);if(r>=d){k.removeData("countTo");clearInterval(p.interval);n=f.to;typeof f.onComplete=="function"&&f.onComplete.call(h,n)}},f.refreshInterval);j(n)})};b.fn.countTo.defaults={from:0,to:0,speed:1E3,refreshInterval:100,decimals:0,formatter:function(a,j){return a.toFixed(j.decimals)},onUpdate:null,onComplete:null}})(jQuery);jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(b,a,j,f,d){return jQuery.easing[jQuery.easing.def](b,a,j,f,d)},easeInQuad:function(b,a,j,f,d){return f*(a/=d)*a+j},easeOutQuad:function(b,a,j,f,d){return-f*(a/=d)*(a-2)+j},easeInOutQuad:function(b,a,j,f,d){if((a/=d/2)<1)return f/2*a*a+j;return-f/2*(--a*(a-2)-1)+j},easeInCubic:function(b,a,j,f,d){return f*(a/=d)*a*a+j},easeOutCubic:function(b,a,j,f,d){return f*((a=a/d-1)*a*a+1)+j},easeInOutCubic:function(b,a,j,f,d){if((a/=d/2)<1)return f/
2*a*a*a+j;return f/2*((a-=2)*a*a+2)+j},easeInQuart:function(b,a,j,f,d){return f*(a/=d)*a*a*a+j},easeOutQuart:function(b,a,j,f,d){return-f*((a=a/d-1)*a*a*a-1)+j},easeInOutQuart:function(b,a,j,f,d){if((a/=d/2)<1)return f/2*a*a*a*a+j;return-f/2*((a-=2)*a*a*a-2)+j},easeInQuint:function(b,a,j,f,d){return f*(a/=d)*a*a*a*a+j},easeOutQuint:function(b,a,j,f,d){return f*((a=a/d-1)*a*a*a*a+1)+j},easeInOutQuint:function(b,a,j,f,d){if((a/=d/2)<1)return f/2*a*a*a*a*a+j;return f/2*((a-=2)*a*a*a*a+2)+j},easeInSine:function(b,
a,j,f,d){return-f*Math.cos(a/d*(Math.PI/2))+f+j},easeOutSine:function(b,a,j,f,d){return f*Math.sin(a/d*(Math.PI/2))+j},easeInOutSine:function(b,a,j,f,d){return-f/2*(Math.cos(Math.PI*a/d)-1)+j},easeInExpo:function(b,a,j,f,d){return a==0?j:f*Math.pow(2,10*(a/d-1))+j},easeOutExpo:function(b,a,j,f,d){return a==d?j+f:f*(-Math.pow(2,-10*a/d)+1)+j},easeInOutExpo:function(b,a,j,f,d){if(a==0)return j;if(a==d)return j+f;if((a/=d/2)<1)return f/2*Math.pow(2,10*(a-1))+j;return f/2*(-Math.pow(2,-10*--a)+2)+j},
easeInCirc:function(b,a,j,f,d){return-f*(Math.sqrt(1-(a/=d)*a)-1)+j},easeOutCirc:function(b,a,j,f,d){return f*Math.sqrt(1-(a=a/d-1)*a)+j},easeInOutCirc:function(b,a,j,f,d){if((a/=d/2)<1)return-f/2*(Math.sqrt(1-a*a)-1)+j;return f/2*(Math.sqrt(1-(a-=2)*a)+1)+j},easeInElastic:function(b,a,j,f,d){var g=0,h=f;if(a==0)return j;if((a/=d)==1)return j+f;g||(g=d*0.3);if(h<Math.abs(f)){h=f;b=g/4}else b=g/(2*Math.PI)*Math.asin(f/h);return-(h*Math.pow(2,10*(a-=1))*Math.sin((a*d-b)*2*Math.PI/g))+j},easeOutElastic:function(b,
a,j,f,d){var g=0,h=f;if(a==0)return j;if((a/=d)==1)return j+f;g||(g=d*0.3);if(h<Math.abs(f)){h=f;b=g/4}else b=g/(2*Math.PI)*Math.asin(f/h);return h*Math.pow(2,-10*a)*Math.sin((a*d-b)*2*Math.PI/g)+f+j},easeInOutElastic:function(b,a,j,f,d){var g=0,h=f;if(a==0)return j;if((a/=d/2)==2)return j+f;g||(g=d*0.3*1.5);if(h<Math.abs(f)){h=f;b=g/4}else b=g/(2*Math.PI)*Math.asin(f/h);if(a<1)return-0.5*h*Math.pow(2,10*(a-=1))*Math.sin((a*d-b)*2*Math.PI/g)+j;return h*Math.pow(2,-10*(a-=1))*Math.sin((a*d-b)*2*Math.PI/
g)*0.5+f+j},easeInBack:function(b,a,j,f,d,g){if(g==undefined)g=1.70158;return f*(a/=d)*a*((g+1)*a-g)+j},easeOutBack:function(b,a,j,f,d,g){if(g==undefined)g=1.70158;return f*((a=a/d-1)*a*((g+1)*a+g)+1)+j},easeInOutBack:function(b,a,j,f,d,g){if(g==undefined)g=1.70158;if((a/=d/2)<1)return f/2*a*a*(((g*=1.525)+1)*a-g)+j;return f/2*((a-=2)*a*(((g*=1.525)+1)*a+g)+2)+j},easeInBounce:function(b,a,j,f,d){return f-jQuery.easing.easeOutBounce(b,d-a,0,f,d)+j},easeOutBounce:function(b,a,j,f,d){return(a/=d)<1/
2.75?f*7.5625*a*a+j:a<2/2.75?f*(7.5625*(a-=1.5/2.75)*a+0.75)+j:a<2.5/2.75?f*(7.5625*(a-=2.25/2.75)*a+0.9375)+j:f*(7.5625*(a-=2.625/2.75)*a+0.984375)+j},easeInOutBounce:function(b,a,j,f,d){if(a<d/2)return jQuery.easing.easeInBounce(b,a*2,0,f,d)*0.5+j;return jQuery.easing.easeOutBounce(b,a*2-d,0,f,d)*0.5+f*0.5+j}});
(function(b){"function"==typeof define&&define.amd?define(["jquery"],b):b(jQuery)})(function(b){function a(d,g,h){var k=g.hash.slice(1),r=document.getElementById(k)||document.getElementsByName(k)[0];if(r){d&&d.preventDefault();var n=b(h.target);if(!(h.lock&&n.is(":animated")||h.onBefore&&false===h.onBefore(d,r,n))){if(h.stop&&n.stop(true),h.hash){d=r.id===k?"id":"name";var p=b("<a> </a>").attr(d,k).css({position:"absolute",top:b(window).scrollTop(),left:b(window).scrollLeft()});r[d]="";b("body").prepend(p);
location.hash=g.hash;p.remove();r[d]=k}n.scrollTo(r,h).trigger("notify.serialScroll",[r])}}}var j=location.href.replace(/#.*/,""),f=b.localScroll=function(d){b("body").localScroll(d)};return f.defaults={duration:1E3,axis:"y",event:"click",stop:true,target:window,autoscroll:true},b.fn.localScroll=function(d){function g(){return!!this.href&&!!this.hash&&this.href.replace(this.hash,"")===j&&(!d.filter||b(this).is(d.filter))}return(d=b.extend({},f.defaults,d)).autoscroll&&d.hash&&location.hash&&(d.target&&
window.scrollTo(0,0),a(0,location,d)),d.lazy?this.on(d.event,"a,area",function(h){g.call(this)&&a(h,this,d)}):this.find("a,area").filter(g).bind(d.event,function(h){a(h,this,d)}).end().end()},f.hash=function(){},f});$(document).ready(function(){var b=$(".countdown"),a=b.attr("data-finish-date"),j=b.attr("data-UTC"),f=b.attr("data-finish-message");b.downCount({date:a,offset:j},function(){alert(f)})});
(function(b){b.fn.downCount=function(a,j){var f=b.extend({date:null,offset:null},a);f.date||b.error("Date is not defined.");Date.parse(f.date)||b.error("Incorrect date format, it should look like this, 12/24/2012 12:00:00.");var d=this,g=setInterval(function(){var h=new Date(f.date),k=new Date;k=k.getTime()+k.getTimezoneOffset()*6E4;var r=h-new Date(k+36E5*f.offset);if(r<0){clearInterval(g);j&&typeof j==="function"&&j()}else{h=Math.floor(r/864E5);k=Math.floor(r%864E5/36E5);var n=Math.floor(r%36E5/
6E4);r=Math.floor(r%6E4/1E3);h=String(h).length>=2?h:"0"+h;k=String(k).length>=2?k:"0"+k;n=String(n).length>=2?n:"0"+n;r=String(r).length>=2?r:"0"+r;var p=h===1?"day":"days",o=k===1?"hour":"hours",m=n===1?"minute":"minutes",q=r===1?"second":"seconds";d.find(".days").text(h);d.find(".hours").text(k);d.find(".minutes").text(n);d.find(".seconds").text(r);d.find(".days_ref").text(p);d.find(".hours_ref").text(o);d.find(".minutes_ref").text(m);d.find(".seconds_ref").text(q)}},300)}})(jQuery);
(function(b,a,j,f){var d=b(a);b.fn.lazyload=function(g){function h(){var p=0;r.each(function(){var o=b(this);if(!n.skip_invisible||o.is(":visible"))if(!(b.abovethetop(this,n)||b.leftofbegin(this,n)))if(b.belowthefold(this,n)||b.rightoffold(this,n)){if(++p>n.failure_limit)return false}else{o.trigger("appear");p=0}})}var k,r=this,n={threshold:0,failure_limit:0,event:"scroll",effect:"show",container:a,data_attribute:"original",skip_invisible:false,appear:null,load:null,placeholder:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"};
return g&&(f!==g.failurelimit&&(g.failure_limit=g.failurelimit,delete g.failurelimit),f!==g.effectspeed&&(g.effect_speed=g.effectspeed,delete g.effectspeed),b.extend(n,g)),k=n.container===f||n.container===a?d:b(n.container),0===n.event.indexOf("scroll")&&k.bind(n.event,function(){return h()}),this.each(function(){var p=this,o=b(p);p.loaded=false;(o.attr("src")===f||o.attr("src")===false)&&o.is("img")&&o.attr("src",n.placeholder);o.one("appear",function(){if(!this.loaded){n.appear&&n.appear.call(p,
r.length,n);b("<img />").bind("load",function(){var m=o.attr("data-"+n.data_attribute);o.hide();o.is("img")?o.attr("src",m):o.css("background-image","url('"+m+"')");o[n.effect](n.effect_speed);p.loaded=true;m=b.grep(r,function(q){return!q.loaded});if(r=b(m),n.load)n.load.call(p,r.length,n)}).attr("src",o.attr("data-"+n.data_attribute))}});0!==n.event.indexOf("scroll")&&o.bind(n.event,function(){p.loaded||o.trigger("appear")})}),d.bind("resize",function(){h()}),/(?:iphone|ipod|ipad).*os 5/gi.test(navigator.appVersion)&&
d.bind("pageshow",function(p){p.originalEvent&&p.originalEvent.persisted&&r.each(function(){b(this).trigger("appear")})}),b(j).ready(function(){h()}),this};b.belowthefold=function(g,h){var k;return k=h.container===f||h.container===a?(a.innerHeight?a.innerHeight:d.height())+d.scrollTop():b(h.container).offset().top+b(h.container).height(),k<=b(g).offset().top-h.threshold};b.rightoffold=function(g,h){var k;return k=h.container===f||h.container===a?d.width()+d.scrollLeft():b(h.container).offset().left+
b(h.container).width(),k<=b(g).offset().left-h.threshold};b.abovethetop=function(g,h){var k;return k=h.container===f||h.container===a?d.scrollTop():b(h.container).offset().top,k>=b(g).offset().top+h.threshold+b(g).height()};b.leftofbegin=function(g,h){var k;return k=h.container===f||h.container===a?d.scrollLeft():b(h.container).offset().left,k>=b(g).offset().left+h.threshold+b(g).width()};b.inviewport=function(g,h){return!(b.rightoffold(g,h)||b.leftofbegin(g,h)||b.belowthefold(g,h)||b.abovethetop(g,
h))};b.extend(b.expr[":"],{"below-the-fold":function(g){return b.belowthefold(g,{threshold:0})},"above-the-top":function(g){return!b.belowthefold(g,{threshold:0})},"right-of-screen":function(g){return b.rightoffold(g,{threshold:0})},"left-of-screen":function(g){return!b.rightoffold(g,{threshold:0})},"in-viewport":function(g){return b.inviewport(g,{threshold:0})},"above-the-fold":function(g){return!b.belowthefold(g,{threshold:0})},"right-of-fold":function(g){return b.rightoffold(g,{threshold:0})},
"left-of-fold":function(g){return!b.rightoffold(g,{threshold:0})}})})(jQuery,window,document);(function(b){b(".img-lazy").lazyload({effect:"fadeIn",effectspeed:1E3,skip_invisible:false,threshold:200});b(".img-lazy-work").lazyload({effect:"fadeIn",effectspeed:1E3,skip_invisible:false,threshold:200})})(jQuery);
(function(b){"function"==typeof define&&define.amd?define(["jquery"],b):b("object"==typeof exports?require("jquery"):window.jQuery||window.Zepto)})(function(b){var a,j,f,d,g,h,k=function(){},r=!!window.jQuery,n=b(window),p=function(c,e){a.ev.on("mfp"+c+".mfp",e)},o=function(c,e,i,l){var s=document.createElement("div");return s.className="mfp-"+c,i&&(s.innerHTML=i),l?e&&e.appendChild(s):(s=b(s),e&&s.appendTo(e)),s},m=function(c,e){a.ev.triggerHandler("mfp"+c,e);a.st.callbacks&&(c=c.charAt(0).toLowerCase()+
c.slice(1),a.st.callbacks[c]&&a.st.callbacks[c].apply(a,b.isArray(e)?e:[e]))},q=function(c){return c===h&&a.currTemplate.closeBtn||(a.currTemplate.closeBtn=b(a.st.closeMarkup.replace("%title%",a.st.tClose)),h=c),a.currTemplate.closeBtn},v=function(){b.magnificPopup.instance||(a=new k,a.init(),b.magnificPopup.instance=a)},t=function(){var c=document.createElement("p").style,e=["ms","O","Moz","Webkit"];if(void 0!==c.transition)return true;for(;e.length;)if(e.pop()+"Transition"in c)return true;return false};
k.prototype={constructor:k,init:function(){var c=navigator.appVersion;a.isIE7=-1!==c.indexOf("MSIE 7.");a.isIE8=-1!==c.indexOf("MSIE 8.");a.isLowIE=a.isIE7||a.isIE8;a.isAndroid=/android/gi.test(c);a.isIOS=/iphone|ipad|ipod/gi.test(c);a.supportsTransition=t();a.probablyMobile=a.isAndroid||a.isIOS||/(Opera Mini)|Kindle|webOS|BlackBerry|(Opera Mobi)|(Windows Phone)|IEMobile/i.test(navigator.userAgent);f=b(document);a.popupsCache={}},open:function(c){var e;if(c.isObj===false){a.items=c.items.toArray();
a.index=0;var i,l=c.items;for(e=0;e<l.length;e++)if(i=l[e],i.parsed&&(i=i.el[0]),i===c.el[0]){a.index=e;break}}else{a.items=b.isArray(c.items)?c.items:[c.items];a.index=c.index||0}if(a.isOpen)return void a.updateItemHTML();a.types=[];g="";a.ev=c.mainEl&&c.mainEl.length?c.mainEl.eq(0):f;c.key?(a.popupsCache[c.key]||(a.popupsCache[c.key]={}),a.currTemplate=a.popupsCache[c.key]):a.currTemplate={};a.st=b.extend(true,{},b.magnificPopup.defaults,c);a.fixedContentPos="auto"===a.st.fixedContentPos?!a.probablyMobile:
a.st.fixedContentPos;a.st.modal&&(a.st.closeOnContentClick=false,a.st.closeOnBgClick=false,a.st.showCloseBtn=false,a.st.enableEscapeKey=false);a.bgOverlay||(a.bgOverlay=o("bg").on("click.mfp",function(){a.close()}),a.wrap=o("wrap").attr("tabindex",-1).on("click.mfp",function(s){a._checkIfClose(s.target)&&a.close()}),a.container=o("container",a.wrap));a.contentContainer=o("content");a.st.preloader&&(a.preloader=o("preloader",a.container,a.st.tLoading));i=b.magnificPopup.modules;for(e=0;e<i.length;e++){l=
i[e];l=l.charAt(0).toUpperCase()+l.slice(1);a["init"+l].call(a)}m("BeforeOpen");a.st.showCloseBtn&&(a.st.closeBtnInside?(p("MarkupParse",function(s,w,x,y){x.close_replaceWith=q(y.type)}),g+=" mfp-close-btn-in"):a.wrap.append(q()));a.st.alignTop&&(g+=" mfp-align-top");a.wrap.css(a.fixedContentPos?{overflow:a.st.overflowY,overflowX:"hidden",overflowY:a.st.overflowY}:{top:n.scrollTop(),position:"absolute"});(a.st.fixedBgPos===false||"auto"===a.st.fixedBgPos&&!a.fixedContentPos)&&a.bgOverlay.css({height:f.height(),
position:"absolute"});a.st.enableEscapeKey&&f.on("keyup.mfp",function(s){27===s.keyCode&&a.close()});n.on("resize.mfp",function(){a.updateSize()});a.st.closeOnContentClick||(g+=" mfp-auto-cursor");g&&a.wrap.addClass(g);e=a.wH=n.height();i={};if(a.fixedContentPos&&a._hasScrollBar(e))(l=a._getScrollbarSize())&&(i.marginRight=l);a.fixedContentPos&&(a.isIE7?b("body, html").css("overflow","hidden"):i.overflow="hidden");l=a.st.mainClass;return a.isIE7&&(l+=" mfp-ie7"),l&&a._addClassToMFP(l),a.updateItemHTML(),
m("BuildControls"),b("html").css(i),a.bgOverlay.add(a.wrap).prependTo(a.st.prependTo||b(document.body)),a._lastFocusedEl=document.activeElement,setTimeout(function(){a.content?(a._addClassToMFP("mfp-ready"),a._setFocus()):a.bgOverlay.addClass("mfp-ready");f.on("focusin.mfp",a._onFocusIn)},16),a.isOpen=true,a.updateSize(e),m("Open"),c},close:function(){a.isOpen&&(m("BeforeClose"),a.isOpen=false,a.st.removalDelay&&!a.isLowIE&&a.supportsTransition?(a._addClassToMFP("mfp-removing"),setTimeout(function(){a._close()},
a.st.removalDelay)):a._close())},_close:function(){m("Close");var c="mfp-removing mfp-ready ";if(a.bgOverlay.detach(),a.wrap.detach(),a.container.empty(),a.st.mainClass&&(c+=a.st.mainClass+" "),a._removeClassFromMFP(c),a.fixedContentPos){c={marginRight:""};a.isIE7?b("body, html").css("overflow",""):c.overflow="";b("html").css(c)}f.off("keyup.mfp focusin.mfp");a.ev.off(".mfp");a.wrap.attr("class","mfp-wrap").removeAttr("style");a.bgOverlay.attr("class","mfp-bg");a.container.attr("class","mfp-container");
!a.st.showCloseBtn||a.st.closeBtnInside&&a.currTemplate[a.currItem.type]!==true||a.currTemplate.closeBtn&&a.currTemplate.closeBtn.detach();a._lastFocusedEl&&b(a._lastFocusedEl).focus();a.currItem=null;a.content=null;a.currTemplate=null;a.prevHeight=0;m("AfterClose")},updateSize:function(c){if(a.isIOS){c=window.innerHeight*(document.documentElement.clientWidth/window.innerWidth);a.wrap.css("height",c);a.wH=c}else a.wH=c||n.height();a.fixedContentPos||a.wrap.css("height",a.wH);m("Resize")},updateItemHTML:function(){var c=
a.items[a.index];a.contentContainer.detach();a.content&&a.content.detach();c.parsed||(c=a.parseEl(a.index));var e=c.type;if(m("BeforeChange",[a.currItem?a.currItem.type:"",e]),a.currItem=c,!a.currTemplate[e]){var i=a.st[e]?a.st[e].markup:false;m("FirstMarkupParse",i);a.currTemplate[e]=i?b(i):true}d&&d!==c.type&&a.container.removeClass("mfp-"+d+"-holder");i=a["get"+e.charAt(0).toUpperCase()+e.slice(1)](c,a.currTemplate[e]);a.appendContent(i,e);c.preloaded=true;m("Change",c);d=c.type;a.container.prepend(a.contentContainer);
m("AfterChange")},appendContent:function(c,e){(a.content=c)?a.st.showCloseBtn&&a.st.closeBtnInside&&a.currTemplate[e]===true?a.content.find(".mfp-close").length||a.content.append(q()):a.content=c:a.content="";m("BeforeAppend");a.container.addClass("mfp-"+e+"-holder");a.contentContainer.append(a.content)},parseEl:function(c){var e,i=a.items[c];if(i.tagName?i={el:b(i)}:(e=i.type,i={data:i,src:i.src}),i.el){for(var l=a.types,s=0;s<l.length;s++)if(i.el.hasClass("mfp-"+l[s])){e=l[s];break}i.src=i.el.attr("data-mfp-src");
i.src||(i.src=i.el.attr("href"))}return i.type=e||a.st.type||"inline",i.index=c,i.parsed=true,a.items[c]=i,m("ElementParse",i),a.items[c]},addGroup:function(c,e){var i=function(l){l.mfpEl=this;a._openClick(l,c,e)};e||(e={});e.mainEl=c;e.items?(e.isObj=true,c.off("click.magnificPopup").on("click.magnificPopup",i)):(e.isObj=false,e.delegate?c.off("click.magnificPopup").on("click.magnificPopup",e.delegate,i):(e.items=c,c.off("click.magnificPopup").on("click.magnificPopup",i)))},_openClick:function(c,
e,i){if((void 0!==i.midClick?i.midClick:b.magnificPopup.defaults.midClick)||2!==c.which&&!c.ctrlKey&&!c.metaKey){var l=void 0!==i.disableOn?i.disableOn:b.magnificPopup.defaults.disableOn;if(l)if(b.isFunction(l)){if(!l.call(a))return true}else if(n.width()<l)return true;c.type&&(c.preventDefault(),a.isOpen&&c.stopPropagation());i.el=b(c.mfpEl);i.delegate&&(i.items=e.find(i.delegate));a.open(i)}},updateStatus:function(c,e){if(a.preloader){j!==c&&a.container.removeClass("mfp-s-"+j);e||"loading"!==c||
(e=a.st.tLoading);var i={status:c,text:e};m("UpdateStatus",i);c=i.status;e=i.text;a.preloader.html(e);a.preloader.find("a").on("click",function(l){l.stopImmediatePropagation()});a.container.addClass("mfp-s-"+c);j=c}},_checkIfClose:function(c){if(!b(c).hasClass("mfp-prevent-close")){var e=a.st.closeOnContentClick,i=a.st.closeOnBgClick;if(e&&i)return true;if(!a.content||b(c).hasClass("mfp-close")||a.preloader&&c===a.preloader[0])return true;if(c===a.content[0]||b.contains(a.content[0],c)){if(e)return true}else if(i&&
b.contains(document,c))return true;return false}},_addClassToMFP:function(c){a.bgOverlay.addClass(c);a.wrap.addClass(c)},_removeClassFromMFP:function(c){this.bgOverlay.removeClass(c);a.wrap.removeClass(c)},_hasScrollBar:function(c){return(a.isIE7?f.height():document.body.scrollHeight)>(c||n.height())},_setFocus:function(){(a.st.focus?a.content.find(a.st.focus).eq(0):a.wrap).focus()},_onFocusIn:function(c){return c.target===a.wrap[0]||b.contains(a.wrap[0],c.target)?void 0:(a._setFocus(),false)},_parseMarkup:function(c,
e,i){var l;i.data&&(e=b.extend(i.data,e));m("MarkupParse",[c,e,i]);b.each(e,function(s,w){if(void 0===w||w===false)return true;if(l=s.split("_"),l.length>1){var x=c.find(".mfp-"+l[0]);if(x.length>0){var y=l[1];"replaceWith"===y?x[0]!==w[0]&&x.replaceWith(w):"img"===y?x.is("img")?x.attr("src",w):x.replaceWith('<img src="'+w+'" class="'+x.attr("class")+'" />'):x.attr(l[1],w)}}else c.find(".mfp-"+s).html(w)})},_getScrollbarSize:function(){if(void 0===a.scrollbarSize){var c=document.createElement("div");
c.style.cssText="width: 99px; height: 99px; overflow: scroll; position: absolute; top: -9999px;";document.body.appendChild(c);a.scrollbarSize=c.offsetWidth-c.clientWidth;document.body.removeChild(c)}return a.scrollbarSize}};b.magnificPopup={instance:null,proto:k.prototype,modules:[],open:function(c,e){return v(),c=c?b.extend(true,{},c):{},c.isObj=true,c.index=e||0,this.instance.open(c)},close:function(){return b.magnificPopup.instance&&b.magnificPopup.instance.close()},registerModule:function(c,e){e.options&&
(b.magnificPopup.defaults[c]=e.options);b.extend(this.proto,e.proto);this.modules.push(c)},defaults:{disableOn:0,key:null,midClick:false,mainClass:"",preloader:true,focus:"",closeOnContentClick:false,closeOnBgClick:true,closeBtnInside:true,showCloseBtn:true,enableEscapeKey:true,modal:false,alignTop:false,removalDelay:0,prependTo:null,fixedContentPos:"auto",fixedBgPos:"auto",overflowY:"auto",closeMarkup:'<button title="%title%" type="button" class="mfp-close">×</button>',tClose:"Close (Esc)",
tLoading:"Loading..."}};b.fn.magnificPopup=function(c){v();var e=b(this);if("string"==typeof c)if("open"===c){var i,l=r?e.data("magnificPopup"):e[0].magnificPopup,s=parseInt(arguments[1],10)||0;l.items?i=l.items[s]:(i=e,l.delegate&&(i=i.find(l.delegate)),i=i.eq(s));a._openClick({mfpEl:i},e,l)}else a.isOpen&&a[c].apply(a,Array.prototype.slice.call(arguments,1));else{c=b.extend(true,{},c);r?e.data("magnificPopup",c):e[0].magnificPopup=c;a.addGroup(e,c)}return e};var u,A,B,C=function(){B&&(A.after(B.addClass(u)).detach(),
B=null)};b.magnificPopup.registerModule("inline",{options:{hiddenClass:"hide",markup:"",tNotFound:"Content not found"},proto:{initInline:function(){a.types.push("inline");p("Close.inline",function(){C()})},getInline:function(c,e){if(C(),c.src){var i=a.st.inline,l=b(c.src);if(l.length){var s=l[0].parentNode;s&&s.tagName&&(A||(u=i.hiddenClass,A=o(u),u="mfp-"+u),B=l.after(A).detach().removeClass(u));a.updateStatus("ready")}else{a.updateStatus("error",i.tNotFound);l=b("<div>")}return c.inlineElement=
l,l}return a.updateStatus("ready"),a._parseMarkup(e,{},c),e}}});var z,G=function(){z&&b(document.body).removeClass(z)},H=function(){G();a.req&&a.req.abort()};b.magnificPopup.registerModule("ajax",{options:{settings:null,cursor:"mfp-ajax-cur",tError:'<a href="%url%">The content</a> could not be loaded.'},proto:{initAjax:function(){a.types.push("ajax");z=a.st.ajax.cursor;p("Close.ajax",H);p("BeforeChange.ajax",H)},getAjax:function(c){z&&b(document.body).addClass(z);a.updateStatus("loading");var e=b.extend({url:c.src,
success:function(i,l,s){i={data:i,xhr:s};m("ParseAjax",i);a.appendContent(b(i.data),"ajax");c.finished=true;G();a._setFocus();setTimeout(function(){a.wrap.addClass("mfp-ready")},16);a.updateStatus("ready");m("AjaxContentAdded")},error:function(){G();c.finished=c.loadError=true;a.updateStatus("error",a.st.ajax.tError.replace("%url%",c.src))}},a.st.ajax.settings);return a.req=b.ajax(e),""}}});var E,P=function(c){if(c.data&&void 0!==c.data.title)return c.data.title;var e=a.st.image.titleSrc;if(e){if(b.isFunction(e))return e.call(a,
c);if(c.el)return c.el.attr(e)||""}return""};b.magnificPopup.registerModule("image",{options:{markup:'<div class="mfp-figure"><div class="mfp-close"></div><figure><div class="mfp-img"></div><figcaption><div class="mfp-bottom-bar"><div class="mfp-title"></div><div class="mfp-counter"></div></div></figcaption></figure></div>',cursor:"mfp-zoom-out-cur",titleSrc:"title",verticalFit:true,tError:'<a href="%url%">The image</a> could not be loaded.'},proto:{initImage:function(){var c=a.st.image;a.types.push("image");
p("Open.image",function(){"image"===a.currItem.type&&c.cursor&&b(document.body).addClass(c.cursor)});p("Close.image",function(){c.cursor&&b(document.body).removeClass(c.cursor);n.off("resize.mfp")});p("Resize.image",a.resizeImage);a.isLowIE&&p("AfterChange",a.resizeImage)},resizeImage:function(){var c=a.currItem;if(c&&c.img&&a.st.image.verticalFit){var e=0;a.isLowIE&&(e=parseInt(c.img.css("padding-top"),10)+parseInt(c.img.css("padding-bottom"),10));c.img.css("max-height",a.wH-e)}},_onImageHasSize:function(c){c.img&&
(c.hasSize=true,E&&clearInterval(E),c.isCheckingImgSize=false,m("ImageHasSize",c),c.imgHidden&&(a.content&&a.content.removeClass("mfp-loading"),c.imgHidden=false))},findImageSize:function(c){var e=0,i=c.img[0],l=function(s){E&&clearInterval(E);E=setInterval(function(){return i.naturalWidth>0?void a._onImageHasSize(c):(e>200&&clearInterval(E),e++,void(3===e?l(10):40===e?l(50):100===e&&l(500)))},s)};l(1)},getImage:function(c,e){var i=0,l=function(){c&&(c.img[0].complete?(c.img.off(".mfploader"),c===
a.currItem&&(a._onImageHasSize(c),a.updateStatus("ready")),c.hasSize=true,c.loaded=true,m("ImageLoadComplete")):(i++,200>i?setTimeout(l,100):s()))},s=function(){c&&(c.img.off(".mfploader"),c===a.currItem&&(a._onImageHasSize(c),a.updateStatus("error",w.tError.replace("%url%",c.src))),c.hasSize=true,c.loaded=true,c.loadError=true)},w=a.st.image,x=e.find(".mfp-img");if(x.length){var y=document.createElement("img");y.className="mfp-img";c.el&&c.el.find("img").length&&(y.alt=c.el.find("img").attr("alt"));
c.img=b(y).on("load.mfploader",l).on("error.mfploader",s);y.src=c.src;x.is("img")&&(c.img=c.img.clone());y=c.img[0];y.naturalWidth>0?c.hasSize=true:y.width||(c.hasSize=false)}return a._parseMarkup(e,{title:P(c),img_replaceWith:c.img},c),a.resizeImage(),c.hasSize?(E&&clearInterval(E),c.loadError?(e.addClass("mfp-loading"),a.updateStatus("error",w.tError.replace("%url%",c.src))):(e.removeClass("mfp-loading"),a.updateStatus("ready")),e):(a.updateStatus("loading"),c.loading=true,c.hasSize||(c.imgHidden=
true,e.addClass("mfp-loading"),a.findImageSize(c)),e)}}});var J;b.magnificPopup.registerModule("zoom",{options:{enabled:false,easing:"ease-in-out",duration:300,opener:function(c){return c.is("img")?c:c.find("img")}},proto:{initZoom:function(){var c,e=a.st.zoom;if(e.enabled&&a.supportsTransition){var i,l,s=e.duration,w=function(y){y=y.clone().removeAttr("style").removeAttr("class").addClass("mfp-animated-image");var F={position:"fixed",zIndex:9999,left:0,top:0,"-webkit-backface-visibility":"hidden"};
return F["-webkit-transition"]=F["-moz-transition"]=F["-o-transition"]=F.transition="all "+e.duration/1E3+"s "+e.easing,y.css(F),y},x=function(){a.content.css("visibility","visible")};p("BuildControls.zoom",function(){if(a._allowZoom()){if(clearTimeout(i),a.content.css("visibility","hidden"),c=a._getItemToZoom(),!c)return void x();l=w(c);l.css(a._getOffset());a.wrap.append(l);i=setTimeout(function(){l.css(a._getOffset(true));i=setTimeout(function(){x();setTimeout(function(){l.remove();c=l=null;m("ZoomAnimationEnded")},
16)},s)},16)}});p("BeforeClose.zoom",function(){if(a._allowZoom()){if(clearTimeout(i),a.st.removalDelay=s,!c){if(c=a._getItemToZoom(),!c)return;l=w(c)}l.css(a._getOffset(true));a.wrap.append(l);a.content.css("visibility","hidden");setTimeout(function(){l.css(a._getOffset())},16)}});p("Close.zoom",function(){a._allowZoom()&&(x(),l&&l.remove(),c=null)})}},_allowZoom:function(){return"image"===a.currItem.type},_getItemToZoom:function(){return a.currItem.hasSize?a.currItem.img:false},_getOffset:function(c){var e;
e=c?a.currItem.img:a.st.zoom.opener(a.currItem.el||a.currItem);c=e.offset();var i=parseInt(e.css("padding-top"),10),l=parseInt(e.css("padding-bottom"),10);c.top-=b(window).scrollTop()-i;e={width:e.width(),height:(r?e.innerHeight():e[0].offsetHeight)-l-i};return(void 0===J&&(J=void 0!==document.createElement("p").style.MozTransform),J)?e["-moz-transform"]=e.transform="translate("+c.left+"px,"+c.top+"px)":(e.left=c.left,e.top=c.top),e}}});var K=function(c){if(a.currTemplate.iframe){var e=a.currTemplate.iframe.find("iframe");
e.length&&(c||(e[0].src="//about:blank"),a.isIE8&&e.css("display",c?"block":"none"))}};b.magnificPopup.registerModule("iframe",{options:{markup:'<div class="mfp-iframe-scaler"><div class="mfp-close"></div><iframe class="mfp-iframe" src="//about:blank" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',srcAction:"iframe_src",patterns:{youtube:{index:"youtube.com",id:"v=",src:"https://www.youtube.com/embed/%id%?autoplay=1"},
vimeo:{index:"vimeo.com/",id:"/",src:"//player.vimeo.com/video/%id%?autoplay=1"},gmaps:{index:"//maps.google.",src:"%id%&output=embed"}}},proto:{initIframe:function(){a.types.push("iframe");p("BeforeChange",function(c,e,i){e!==i&&(e==="iframe"?K():i==="iframe"&&K(true))});p("Close.iframe",function(){K()})},getIframe:function(c,e){var i=c.src,l=a.st.iframe;b.each(l.patterns,function(){return i.indexOf(this.index)>-1?(this.id&&(i="string"==typeof this.id?i.substr(i.lastIndexOf(this.id)+this.id.length,
i.length):this.id.call(this,i)),i=this.src.replace("%id%",i),false):void 0});var s={};return l.srcAction&&(s[l.srcAction]=i),a._parseMarkup(e,s,c),a.updateStatus("ready"),e}}});var L=function(c){var e=a.items.length;return c>e-1?c-e:0>c?e+c:c};b.magnificPopup.registerModule("gallery",{options:{enabled:false,arrowMarkup:'<button title="%title%" type="button" class="mfp-arrow mfp-arrow-%dir%"></button>',preload:[0,2],navigateByImgClick:true,arrows:true,tPrev:"Previous (Left arrow key)",tNext:"Next (Right arrow key)",
tCounter:"%curr% of %total%"},proto:{initGallery:function(){var c=a.st.gallery,e=Boolean(b.fn.mfpFastClick);return a.direction=true,c&&c.enabled?(g+=" mfp-gallery",p("Open.mfp-gallery",function(){c.navigateByImgClick&&a.wrap.on("click.mfp-gallery",".mfp-img",function(){return a.items.length>1?(a.next(),false):void 0});f.on("keydown.mfp-gallery",function(i){37===i.keyCode?a.prev():39===i.keyCode&&a.next()})}),p("UpdateStatus.mfp-gallery",function(i,l){l.text&&(l.text=l.text.replace(/%curr%/gi,a.currItem.index+
1).replace(/%total%/gi,a.items.length))}),p("MarkupParse.mfp-gallery",function(i,l,s,w){i=a.items.length;s.counter=i>1?c.tCounter.replace(/%curr%/gi,w.index+1).replace(/%total%/gi,i):""}),p("BuildControls.mfp-gallery",function(){if(a.items.length>1&&c.arrows&&!a.arrowLeft){var i=c.arrowMarkup,l=a.arrowLeft=b(i.replace(/%title%/gi,c.tPrev).replace(/%dir%/gi,"left")).addClass("mfp-prevent-close");i=a.arrowRight=b(i.replace(/%title%/gi,c.tNext).replace(/%dir%/gi,"right")).addClass("mfp-prevent-close");
var s=e?"mfpFastClick":"click";l[s](function(){a.prev()});i[s](function(){a.next()});a.isIE7&&(o("b",l[0],false,true),o("a",l[0],false,true),o("b",i[0],false,true),o("a",i[0],false,true));a.container.append(l.add(i))}}),p("Change.mfp-gallery",function(){a._preloadTimeout&&clearTimeout(a._preloadTimeout);a._preloadTimeout=setTimeout(function(){a.preloadNearbyImages();a._preloadTimeout=null},16)}),void p("Close.mfp-gallery",function(){f.off(".mfp-gallery");a.wrap.off("click.mfp-gallery");a.arrowLeft&&
e&&a.arrowLeft.add(a.arrowRight).destroyMfpFastClick();a.arrowRight=a.arrowLeft=null})):false},next:function(){a.direction=true;a.index=L(a.index+1);a.updateItemHTML()},prev:function(){a.direction=false;a.index=L(a.index-1);a.updateItemHTML()},goTo:function(c){a.direction=c>=a.index;a.index=c;a.updateItemHTML()},preloadNearbyImages:function(){var c;c=a.st.gallery.preload;var e=Math.min(c[0],a.items.length),i=Math.min(c[1],a.items.length);for(c=1;c<=(a.direction?i:e);c++)a._preloadItem(a.index+c);
for(c=1;c<=(a.direction?e:i);c++)a._preloadItem(a.index-c)},_preloadItem:function(c){if(c=L(c),!a.items[c].preloaded){var e=a.items[c];e.parsed||(e=a.parseEl(c));m("LazyLoad",e);"image"===e.type&&(e.img=b('<img class="mfp-img" />').on("load.mfploader",function(){e.hasSize=true}).on("error.mfploader",function(){e.hasSize=true;e.loadError=true;m("LazyLoadError",e)}).attr("src",e.src));e.preloaded=true}}}});b.magnificPopup.registerModule("retina",{options:{replaceSrc:function(c){return c.src.replace(/\.\w+$/,
function(e){return"@2x"+e})},ratio:1},proto:{initRetina:function(){if(window.devicePixelRatio>1){var c=a.st.retina,e=c.ratio;e=isNaN(e)?e():e;e>1&&(p("ImageHasSize.retina",function(i,l){l.img.css({"max-width":l.img[0].naturalWidth/e,width:"100%"})}),p("ElementParse.retina",function(i,l){l.src=c.replaceSrc(l,e)}))}}}});(function(){var c="ontouchstart"in window,e=function(){n.off("touchmove"+i+" touchend"+i)},i=".mfpFastClick";b.fn.mfpFastClick=function(l){return b(this).each(function(){var s,w=b(this);
if(c){var x,y,F,M,D,N;w.on("touchstart"+i,function(O){M=false;N=1;D=O.originalEvent?O.originalEvent.touches[0]:O.touches[0];y=D.clientX;F=D.clientY;n.on("touchmove"+i,function(I){D=I.originalEvent?I.originalEvent.touches:I.touches;N=D.length;D=D[0];(Math.abs(D.clientX-y)>10||Math.abs(D.clientY-F)>10)&&(M=true,e())}).on("touchend"+i,function(I){e();M||N>1||(s=true,I.preventDefault(),clearTimeout(x),x=setTimeout(function(){s=false},1E3),l())})})}w.on("click"+i,function(){s||l()})})};b.fn.destroyMfpFastClick=
function(){b(this).off("touchstart"+i+" click"+i);c&&n.off("touchmove"+i+" touchend"+i)}})();v()});
(function(b){var a=b(window),j=a.height();a.resize(function(){j=a.height()});b.fn.parallax=function(f,d,g){function h(){var p=a.scrollTop();k.each(function(){var o=b(this),m=o.offset().top;o=r(o);m+o<p||m>p+j||k.css("backgroundPosition",f+" "+Math.round((n-p)*d)+"px")})}var k=b(this),r,n;k.each(function(){n=k.offset().top});r=g?function(p){return p.outerHeight(true)}:function(p){return p.height()};if(arguments.length<1||f===null)f="50%";if(arguments.length<2||d===null)d=0.1;if(arguments.length<3||
g===null)g=true;a.bind("scroll",h).resize(h);h()}})(jQuery);
(function(b){"function"===typeof define&&define.amd?define(["jquery"],b):"undefined"!==typeof module&&module.exports?module.exports=b(require("jquery")):b(jQuery)})(function(b){function a(d){return!d.nodeName||-1!==b.inArray(d.nodeName.toLowerCase(),["iframe","#document","html","body"])}function j(d){return b.isFunction(d)||b.isPlainObject(d)?d:{top:d,left:d}}var f=b.scrollTo=function(d,g,h){return b(window).scrollTo(d,g,h)};f.defaults={axis:"xy",duration:0,limit:true};b.fn.scrollTo=function(d,g,
h){"object"===typeof g&&(h=g,g=0);"function"===typeof h&&(h={onAfter:h});"max"===d&&(d=9E9);h=b.extend({},f.defaults,h);g=g||h.duration;var k=h.queue&&1<h.axis.length;k&&(g/=2);h.offset=j(h.offset);h.over=j(h.over);return this.each(function(){function r(u){var A=b.extend({},h,{queue:true,duration:g,complete:u&&function(){u.call(p,m,h)}});o.animate(q,A)}if(null!==d){var n=a(this),p=n?this.contentWindow||window:this,o=b(p),m=d,q={},v;switch(typeof m){case "number":case "string":if(/^([+-]=?)?\d+(\.\d+)?(px|%)?$/.test(m)){m=
j(m);break}m=n?b(m):b(m,p);case "object":if(m.length===0)return;if(m.is||m.style)v=(m=b(m)).offset()}var t=b.isFunction(h.offset)&&h.offset(p,m)||h.offset;b.each(h.axis.split(""),function(u,A){var B="x"===A?"Left":"Top",C=B.toLowerCase(),z="scroll"+B,G=o[z](),H=f.max(p,A);v?(q[z]=v[C]+(n?0:G-o.offset()[C]),h.margin&&(q[z]-=parseInt(m.css("margin"+B),10)||0,q[z]-=parseInt(m.css("border"+B+"Width"),10)||0),q[z]+=t[C]||0,h.over[C]&&(q[z]+=m["x"===A?"width":"height"]()*h.over[C])):(B=m[C],q[z]=B.slice&&
"%"===B.slice(-1)?parseFloat(B)/100*H:B);h.limit&&/^\d+$/.test(q[z])&&(q[z]=0>=q[z]?0:Math.min(q[z],H));!u&&1<h.axis.length&&(G===q[z]?q={}:k&&(r(h.onAfterFirst),q={}))});r(h.onAfter)}})};f.max=function(d,g){var h="x"===g?"Width":"Height",k="scroll"+h;if(!a(d))return d[k]-b(d)[h.toLowerCase()]();h="client"+h;var r=d.ownerDocument||d.document,n=r.documentElement;r=r.body;return Math.max(n[k],r[k])-Math.min(n[h],r[h])};b.Tween.propHooks.scrollLeft=b.Tween.propHooks.scrollTop={get:function(d){return b(d.elem)[d.prop]()},
set:function(d){var g=this.get(d);if(d.options.interrupt&&d._last&&d._last!==g)return b(d.elem).stop();var h=Math.round(d.now);g!==h&&(b(d.elem)[d.prop](h),d._last=this.get(d))}};return f});(function(b){b(document).ready(function(){var a=b(".text-rotate"),j=a.html();a.attr("aria-hidden","true");a.before("<span class='sr-only'>"+j+"</span>");a.textrotator({animation:"dissolve",separator:",",speed:4E3})})})(jQuery);
(function(b){var a={animation:"dissolve",separator:",",speed:2E3};b.fn.textrotator=function(j){var f=b.extend({},a,j);return this.each(function(){var d=b(this),g=[];b.each(d.text().split(f.separator),function(h,k){g.push(k)});d.text(g[0]);setInterval(function(){switch(f.animation){case "dissolve":d.animate({textShadowBlur:20,opacity:0},500,function(){k=b.inArray(d.text(),g);if(k+1==g.length)k=-1;d.text(g[k+1]).animate({textShadowBlur:0,opacity:1},500)});break;case "flip":d.find(".back").length>0&&
d.html(d.find(".back").html());var h=d.text(),k=b.inArray(h,g);if(k+1==g.length)k=-1;d.html("");b("<span class='front'>"+h+"</span>").appendTo(d);b("<span class='back'>"+g[k+1]+"</span>").appendTo(d);d.wrapInner("<span class='rotating' ></span>").find(".rotating").hide().addClass("flip").show().css({"-webkit-transform":" rotateY(-180deg)","-moz-transform":" rotateY(-180deg)","-o-transform":" rotateY(-180deg)",transform:" rotateY(-180deg)"});break;case "flipUp":d.find(".back").length>0&&d.html(d.find(".back").html());
h=d.text();k=b.inArray(h,g);if(k+1==g.length)k=-1;d.html("");b("<span class='front'>"+h+"</span>").appendTo(d);b("<span class='back'>"+g[k+1]+"</span>").appendTo(d);d.wrapInner("<span class='rotating' ></span>").find(".rotating").hide().addClass("flip up").show().css({"-webkit-transform":" rotateX(-180deg)","-moz-transform":" rotateX(-180deg)","-o-transform":" rotateX(-180deg)",transform:" rotateX(-180deg)"});break;case "flipCube":d.find(".back").length>0&&d.html(d.find(".back").html());h=d.text();k=b.inArray(h,
g);if(k+1==g.length)k=-1;d.html("");b("<span class='front'>"+h+"</span>").appendTo(d);b("<span class='back'>"+g[k+1]+"</span>").appendTo(d);d.wrapInner("<span class='rotating' ></span>").find(".rotating").hide().addClass("flip cube").show().css({"-webkit-transform":" rotateY(180deg)","-moz-transform":" rotateY(180deg)","-o-transform":" rotateY(180deg)",transform:" rotateY(180deg)"});break;case "flipCubeUp":d.find(".back").length>0&&d.html(d.find(".back").html());h=d.text();k=b.inArray(h,g);if(k+1==g.length)k=
-1;d.html("");b("<span class='front'>"+h+"</span>").appendTo(d);b("<span class='back'>"+g[k+1]+"</span>").appendTo(d);d.wrapInner("<span class='rotating' ></span>").find(".rotating").hide().addClass("flip cube up").show().css({"-webkit-transform":" rotateX(180deg)","-moz-transform":" rotateX(180deg)","-o-transform":" rotateX(180deg)",transform:" rotateX(180deg)"});break;case "spin":d.find(".rotating").length>0&&d.html(d.find(".rotating").html());k=b.inArray(d.text(),g);if(k+1==g.length)k=-1;d.wrapInner("<span class='rotating spin' ></span>").find(".rotating").hide().text(g[k+
1]).show().css({"-webkit-transform":" rotate(0) scale(1)","-moz-transform":"rotate(0) scale(1)","-o-transform":"rotate(0) scale(1)",transform:"rotate(0) scale(1)"});break;case "fade":d.fadeOut(f.speed,function(){k=b.inArray(d.text(),g);if(k+1==g.length)k=-1;d.text(g[k+1]).fadeIn(f.speed)})}},f.speed)})}})(window.jQuery);
(function(b){b.belowthefold=function(a,j){return b(window).height()+b(window).scrollTop()<=b(a).offset().top-j.threshold};b.abovethetop=function(a,j){return b(window).scrollTop()>=b(a).offset().top+b(a).height()-j.threshold};b.rightofscreen=function(a,j){return b(window).width()+b(window).scrollLeft()<=b(a).offset().left-j.threshold};b.leftofscreen=function(a,j){return b(window).scrollLeft()>=b(a).offset().left+b(a).width()-j.threshold};b.inviewport=function(a,j){return!b.rightofscreen(a,j)&&!b.leftofscreen(a,
j)&&!b.belowthefold(a,j)&&!b.abovethetop(a,j)};b.extend(b.expr[":"],{"below-the-fold":function(a){return b.belowthefold(a,{threshold:0})},"above-the-top":function(a){return b.abovethetop(a,{threshold:0})},"left-of-screen":function(a){return b.leftofscreen(a,{threshold:0})},"right-of-screen":function(a){return b.rightofscreen(a,{threshold:0})},"in-viewport":function(a){return b.inviewport(a,{threshold:0})}})})(jQuery);
(function(b){var a=Array.prototype.slice,j=Array.prototype.splice,f={topSpacing:0,bottomSpacing:0,className:"is-sticky",wrapperClassName:"sticky-wrapper",center:false,getWidthFrom:"",widthFromWrapper:true,responsiveWidth:false},d=b(window),g=b(document),h=[],k=d.height(),r=function(){var o=d.scrollTop(),m=g.height(),q=m-k;q=o>q?q-o:0;for(var v=0;v<h.length;v++){var t=h[v],u=t.stickyWrapper.offset().top-t.topSpacing-q;if(o<=u){if(t.currentTop!==null){t.stickyElement.css({width:"",position:"",top:""});
t.stickyElement.parent().removeClass(t.className);t.stickyElement.trigger("sticky-end",[t]);t.currentTop=null}}else{u=m-t.stickyElement.outerHeight()-t.topSpacing-t.bottomSpacing-o-q;if(u<0)u+=t.topSpacing;else u=t.topSpacing;if(t.currentTop!=u){var A;if(t.getWidthFrom)A=b(t.getWidthFrom).width()||null;else if(t.widthFromWrapper)A=t.stickyWrapper.width();if(A==null)A=t.stickyElement.width();t.stickyElement.css("width",A).css("position","fixed").css("top",u);t.stickyElement.parent().addClass(t.className);
t.currentTop===null?t.stickyElement.trigger("sticky-start",[t]):t.stickyElement.trigger("sticky-update",[t]);if(t.currentTop===t.topSpacing&&t.currentTop>u||t.currentTop===null&&u<t.topSpacing)t.stickyElement.trigger("sticky-bottom-reached",[t]);else t.currentTop!==null&&u===t.topSpacing&&t.currentTop<u&&t.stickyElement.trigger("sticky-bottom-unreached",[t]);t.currentTop=u}}}},n=function(){k=d.height();for(var o=0;o<h.length;o++){var m=h[o],q=null;if(m.getWidthFrom){if(m.responsiveWidth===true)q=
b(m.getWidthFrom).width()}else if(m.widthFromWrapper)q=m.stickyWrapper.width();q!=null&&m.stickyElement.css("width",q)}},p={init:function(o){var m=b.extend({},f,o);return this.each(function(){var q=b(this),v=q.attr("id"),t=q.outerHeight();v=v?v+"-"+f.wrapperClassName:f.wrapperClassName;v=b("<div></div>").attr("id",v).addClass(m.wrapperClassName);q.wrapAll(v);v=q.parent();m.center&&v.css({width:q.outerWidth(),marginLeft:"auto",marginRight:"auto"});q.css("float")=="right"&&q.css({"float":"none"}).parent().css({"float":"right"});
v.css("height",t);m.stickyElement=q;m.stickyWrapper=v;m.currentTop=null;h.push(m)})},update:r,unstick:function(){return this.each(function(){for(var o=b(this),m=-1,q=h.length;q-- >0;)if(h[q].stickyElement.get(0)===this){j.call(h,q,1);m=q}if(m!=-1){o.unwrap();o.css({width:"",position:"",top:"","float":""})}})}};if(window.addEventListener){window.addEventListener("scroll",r,false);window.addEventListener("resize",n,false)}else if(window.attachEvent){window.attachEvent("onscroll",r);window.attachEvent("onresize",
n)}b.fn.sticky=function(o){if(p[o])return p[o].apply(this,a.call(arguments,1));else if(typeof o==="object"||!o)return p.init.apply(this,arguments);else b.error("Method "+o+" does not exist on jQuery.sticky")};b.fn.unstick=function(o){if(p[o])return p[o].apply(this,a.call(arguments,1));else if(typeof o==="object"||!o)return p.unstick.apply(this,arguments);else b.error("Method "+o+" does not exist on jQuery.sticky")};b(function(){setTimeout(r,0)})})(jQuery);
