/***************************
DateTime: 2023-01-26, 09:16:27
File list:
* jquery.ajaxchimp.min.js
* jquery.appear.js
* jquery.countTo.js
* jquery.backgroundvideo.min.js
* jquery.downCount.js
* jquery.fitvids.js
* jquery.easing.1.3.js
* jquery.lazyload.min.js
* jquery.localScroll.min.js
* jquery.parallax-1.1.3.js
* jquery.magnific-popup.min.js
* jquery.scrollTo.min.js
* jquery.simple-text-rotator.min.js
* jquery.sticky.js
* jquery.viewport.mini.js
* jquery.mb.YTPlayer.js
*****************************/
(function(b){b.ajaxChimp={responses:{"Thank you! You have subscribed successfully.":0,"Please enter a value":1,"An email address must contain a single @":2,"The domain portion of the email address is invalid (the portion after the @: )":3,"The username portion of the email address is invalid (the portion before the @: )":4,"This email address looks fake or invalid. Please enter a real email address":5},translations:{en:null},init:function(a,i){b(a).ajaxChimp(i)}};b.fn.ajaxChimp=function(a){return b(this).each(function(i,
e){var d=b(e),f=d.find("input[type=email]"),h=d.find("label[for="+f.attr("id")+"]"),k=b.extend({url:d.attr("action"),language:"en"},a),o=k.url.replace("/post?","/post-json?").concat("&c=?");d.attr("novalidate","true");f.attr("name","EMAIL");d.submit(function(){var m,p={},q=d.serializeArray();b.each(q,function(n,r){p[r.name]=r.value});b.ajax({url:o,data:p,success:function(n){if("success"===n.result){m=n.msg;h.removeClass("error").unwrap().wrap("<div class='success'></div>");f.removeClass("error").addClass("valid")}else{f.removeClass("valid").addClass("error");
h.removeClass("valid").unwrap().wrap("<div class='error'></div>");try{var r=n.msg.split(" - ",2);m=void 0!==r[1]&&parseInt(r[0],10).toString()===r[0]?r[1]:n.msg}catch(v){m=n.msg}}"en"!==k.language&&void 0!==b.ajaxChimp.responses[m]&&b.ajaxChimp.translations&&b.ajaxChimp.translations[k.language]&&b.ajaxChimp.translations[k.language][b.ajaxChimp.responses[m]]&&(m=b.ajaxChimp.translations[k.language][b.ajaxChimp.responses[m]]);h.html(m);h.show();k.callback&&k.callback(n)},dataType:"jsonp",error:function(n,
r){console.log("mailchimp ajax submit error: "+r)}});return"en"!==k.language&&b.ajaxChimp.translations&&b.ajaxChimp.translations[k.language]&&b.ajaxChimp.translations[k.language].submit&&(q=b.ajaxChimp.translations[k.language].submit),h.unwrap().wrap("<div class='success'></div>").html("Submitting...").show(),false})}),this}})(jQuery);(function(b){b("#mailchimp").find(".newsletter-field").first().attr("id","newsletter_field");b("#subscribe-result").html("<label for='newsletter_field'></label>");b("#mailchimp").ajaxChimp({url:"https://games.us6.list-manage.com/subscribe/post?u=7d6839817c6c926621240bbda&id=abb7d6b770&f_id=00510fe3f0"})})(jQuery);
(function(b){b.fn.appear=function(a,i){var e=b.extend({data:undefined,one:true,accX:0,accY:0},i);return this.each(function(){var d=b(this);d.appeared=false;if(a){var f=b(window),h=function(){if(d.is(":visible")){var o=f.scrollLeft(),m=f.scrollTop(),p=d.offset(),q=p.left;p=p.top;var n=e.accX,r=e.accY,v=d.height(),s=f.height(),u=d.width(),z=f.width();if(p+v+r>=m&&p<=m+s+r&&q+u+n>=o&&q<=o+z+n)d.appeared||d.trigger("appear",e.data);else d.appeared=false}else d.appeared=false},k=function(){d.appeared=
true;if(e.one){f.unbind("scroll",h);var o=b.inArray(h,b.fn.appear.checks);o>=0&&b.fn.appear.checks.splice(o,1)}a.apply(this,arguments)};if(e.one)d.one("appear",e.data,k);else d.bind("appear",e.data,k);f.scroll(h);b.fn.appear.checks.push(h);h()}else d.trigger("appear",e.data)})};b.extend(b.fn.appear,{checks:[],timeout:null,checkAll:function(){var a=b.fn.appear.checks.length;if(a>0)for(;a--;)b.fn.appear.checks[a]()},run:function(){b.fn.appear.timeout&&clearTimeout(b.fn.appear.timeout);b.fn.appear.timeout=
setTimeout(b.fn.appear.checkAll,20)}});b.each(["append","prepend","after","before","attr","removeAttr","addClass","removeClass","toggleClass","remove","css","show","hide"],function(a,i){var e=b.fn[i];if(e)b.fn[i]=function(){var d=e.apply(this,arguments);b.fn.appear.run();return d}})})(jQuery);
(function(b){b.fn.countTo=function(a){a=b.extend({},b.fn.countTo.defaults,a||{});var i=Math.ceil(a.speed/a.refreshInterval),e=(a.to-a.from)/i;return b(this).each(function(){var d=this,f=0,h=a.from,k=setInterval(function(){h+=e;f++;b(d).html(h.toFixed(a.decimals));typeof a.onUpdate=="function"&&a.onUpdate.call(d,h);if(f>=i){clearInterval(k);h=a.to;typeof a.onComplete=="function"&&a.onComplete.call(d,h)}},a.refreshInterval)})};b.fn.countTo.defaults={from:0,to:100,speed:1E3,refreshInterval:100,decimals:0,
onUpdate:null,onComplete:null}})(jQuery);
(function(b){b.fn.countTo=function(a){a=a||{};return b(this).each(function(){function i(q){q=e.formatter.call(h,q,e);k.text(q)}var e=b.extend({},b.fn.countTo.defaults,{from:b(this).data("from"),to:b(this).data("to"),speed:b(this).data("speed"),refreshInterval:b(this).data("refresh-interval"),decimals:b(this).data("decimals")},a),d=Math.ceil(e.speed/e.refreshInterval),f=(e.to-e.from)/d,h=this,k=b(this),o=0,m=e.from,p=k.data("countTo")||{};k.data("countTo",p);p.interval&&clearInterval(p.interval);p.interval=
setInterval(function(){m+=f;o++;i(m);typeof e.onUpdate=="function"&&e.onUpdate.call(h,m);if(o>=d){k.removeData("countTo");clearInterval(p.interval);m=e.to;typeof e.onComplete=="function"&&e.onComplete.call(h,m)}},e.refreshInterval);i(m)})};b.fn.countTo.defaults={from:0,to:0,speed:1E3,refreshInterval:100,decimals:0,formatter:function(a,i){return a.toFixed(i.decimals)},onUpdate:null,onComplete:null}})(jQuery);
$(document).ready(function(){new $.backgroundVideo($("#video-background-1"),{align:"centerXY",width:1280,height:720,path:"video/",filename:"video",types:["mp4","ogg","webm"],autoplay:true,loop:true});new $.backgroundVideo($("#video-background-2"),{align:"centerXY",width:1280,height:720,path:"video/",filename:"video-restaurant",types:["mp4","ogg","webm"],autoplay:true,loop:true});$(".bg-video-button-muted").click(function(){if($(this).prev().find("#video_background").prop("muted")){$(this).prev().find("#video_background").prop("muted",
false);$(this).find("i").removeClass("fa-volume-off").addClass("fa-volume-up")}else{$(this).prev().find("#video_background").prop("muted",true);$(this).find("i").removeClass("fa-volume-up").addClass("fa-volume-off")}return false})});
(function(b){b.backgroundVideo=function(a,i){var e=this;e.settings={};var d=function(){var f;f=b(window).width();var h=b(window).height(),k=h/e.settings.height;if(f/h>=e.settings.width/e.settings.height)k=f/e.settings.width;f=k;e.$videoEl.width(f*e.settings.width);e.$videoEl.height(f*e.settings.height);if(typeof e.settings.align!=="undefined"){f=(b(window).width()>>1)-(e.$videoEl.width()>>1)|0;h=(b(window).height()>>1)-(e.$videoEl.height()>>1)|0;if(e.settings.align=="centerXY")e.$videoEl.css({left:f,
top:h});else if(e.settings.align=="centerX")e.$videoEl.css("left",f);else e.settings.align=="centerY"&&e.$videoEl.css("top",h)}};e.settings=b.extend({},{videoid:"video_background",autoplay:true,loop:true,preload:true},i);e.el=a;(function(){var f="",h="",k=e.settings.autoplay,o=e.settings.loop;h=e.settings.preload?'preload="auto"':"";f+='<video id="'+e.settings.videoid+'"'+h+(k?'autoplay="autoplay"':"")+(o?'loop="true"':"");if(e.settings.poster)f+=' poster="'+e.settings.poster+'" ';f+='muted playsinline style="display:none;position:absolute;top:0;left:0;bottom:0;right:0;z-index:-100;width:100%;height:100%;">';
for(h=0;h<e.settings.types.length;h++)f+='<source src="'+e.settings.path+e.settings.filename+"."+e.settings.types[h]+'" type="video/'+e.settings.types[h]+'" ></e>';f+="bgvideo</video>";e.el.prepend(f);e.videoEl=document.getElementById(e.settings.videoid);e.$videoEl=b(e.videoEl);e.$videoEl.fadeIn(2E3);d()})();b(window).resize(function(){d()});e.$videoEl.bind("ended",function(){this.play()})}})(jQuery);
$(document).ready(function(){var b=$(".countdown"),a=b.attr("data-finish-date"),i=b.attr("data-UTC"),e=b.attr("data-finish-message");b.downCount({date:a,offset:i},function(){alert(e)})});
(function(b){b.fn.downCount=function(a,i){var e=b.extend({date:null,offset:null},a);e.date||b.error("Date is not defined.");Date.parse(e.date)||b.error("Incorrect date format, it should look like this, 12/24/2012 12:00:00.");var d=this,f=setInterval(function(){var h=new Date(e.date),k=new Date;k=k.getTime()+k.getTimezoneOffset()*6E4;var o=h-new Date(k+36E5*e.offset);if(o<0){clearInterval(f);i&&typeof i==="function"&&i()}else{h=Math.floor(o/864E5);k=Math.floor(o%864E5/36E5);var m=Math.floor(o%36E5/
6E4);o=Math.floor(o%6E4/1E3);h=String(h).length>=2?h:"0"+h;k=String(k).length>=2?k:"0"+k;m=String(m).length>=2?m:"0"+m;o=String(o).length>=2?o:"0"+o;var p=h===1?"day":"days",q=k===1?"hour":"hours",n=m===1?"minute":"minutes",r=o===1?"second":"seconds";d.find(".days").text(h);d.find(".hours").text(k);d.find(".minutes").text(m);d.find(".seconds").text(o);d.find(".days_ref").text(p);d.find(".hours_ref").text(q);d.find(".minutes_ref").text(n);d.find(".seconds_ref").text(r)}},300)}})(jQuery);
(function(b){b.fn.fitVids=function(a){var i={customSelector:null,ignore:null};if(!document.getElementById("fit-vids-style")){var e=document.head||document.getElementsByTagName("head")[0],d=document.createElement("div");d.innerHTML='<p>x</p><style id="fit-vids-style">.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}</style>';
e.appendChild(d.childNodes[1])}a&&b.extend(i,a);return this.each(function(){var f=['iframe[src*="player.vimeo.com"]','iframe[src*="youtube.com"]','iframe[src*="youtube-nocookie.com"]','iframe[src*="kickstarter.com"][src*="video.html"]',"object","embed"];i.customSelector&&f.push(i.customSelector);var h=".fitvidsignore";if(i.ignore)h=h+", "+i.ignore;f=b(this).find(f.join(","));f=f.not("object object");f=f.not(h);f.each(function(k){var o=b(this);if(!(o.parents(h).length>0))if(!(this.tagName.toLowerCase()===
"embed"&&o.parent("object").length||o.parent(".fluid-width-video-wrapper").length)){if(!o.css("height")&&!o.css("width")&&(isNaN(o.attr("height"))||isNaN(o.attr("width")))){o.attr("height",9);o.attr("width",16)}var m=this.tagName.toLowerCase()==="object"||o.attr("height")&&!isNaN(parseInt(o.attr("height"),10))?parseInt(o.attr("height"),10):o.height(),p=!isNaN(parseInt(o.attr("width"),10))?parseInt(o.attr("width"),10):o.width();m/=p;o.attr("id")||o.attr("id","fitvid"+k);o.wrap('<div class="fluid-width-video-wrapper"></div>').parent(".fluid-width-video-wrapper").css("padding-top",
m*100+"%");o.removeAttr("height").removeAttr("width")}})})}})(window.jQuery||window.Zepto);jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(b,a,i,e,d){return jQuery.easing[jQuery.easing.def](b,a,i,e,d)},easeInQuad:function(b,a,i,e,d){return e*(a/=d)*a+i},easeOutQuad:function(b,a,i,e,d){return-e*(a/=d)*(a-2)+i},easeInOutQuad:function(b,a,i,e,d){if((a/=d/2)<1)return e/2*a*a+i;return-e/2*(--a*(a-2)-1)+i},easeInCubic:function(b,a,i,e,d){return e*(a/=d)*a*a+i},easeOutCubic:function(b,a,i,e,d){return e*((a=a/d-1)*a*a+1)+i},easeInOutCubic:function(b,a,i,e,d){if((a/=d/2)<1)return e/
2*a*a*a+i;return e/2*((a-=2)*a*a+2)+i},easeInQuart:function(b,a,i,e,d){return e*(a/=d)*a*a*a+i},easeOutQuart:function(b,a,i,e,d){return-e*((a=a/d-1)*a*a*a-1)+i},easeInOutQuart:function(b,a,i,e,d){if((a/=d/2)<1)return e/2*a*a*a*a+i;return-e/2*((a-=2)*a*a*a-2)+i},easeInQuint:function(b,a,i,e,d){return e*(a/=d)*a*a*a*a+i},easeOutQuint:function(b,a,i,e,d){return e*((a=a/d-1)*a*a*a*a+1)+i},easeInOutQuint:function(b,a,i,e,d){if((a/=d/2)<1)return e/2*a*a*a*a*a+i;return e/2*((a-=2)*a*a*a*a+2)+i},easeInSine:function(b,
a,i,e,d){return-e*Math.cos(a/d*(Math.PI/2))+e+i},easeOutSine:function(b,a,i,e,d){return e*Math.sin(a/d*(Math.PI/2))+i},easeInOutSine:function(b,a,i,e,d){return-e/2*(Math.cos(Math.PI*a/d)-1)+i},easeInExpo:function(b,a,i,e,d){return a==0?i:e*Math.pow(2,10*(a/d-1))+i},easeOutExpo:function(b,a,i,e,d){return a==d?i+e:e*(-Math.pow(2,-10*a/d)+1)+i},easeInOutExpo:function(b,a,i,e,d){if(a==0)return i;if(a==d)return i+e;if((a/=d/2)<1)return e/2*Math.pow(2,10*(a-1))+i;return e/2*(-Math.pow(2,-10*--a)+2)+i},
easeInCirc:function(b,a,i,e,d){return-e*(Math.sqrt(1-(a/=d)*a)-1)+i},easeOutCirc:function(b,a,i,e,d){return e*Math.sqrt(1-(a=a/d-1)*a)+i},easeInOutCirc:function(b,a,i,e,d){if((a/=d/2)<1)return-e/2*(Math.sqrt(1-a*a)-1)+i;return e/2*(Math.sqrt(1-(a-=2)*a)+1)+i},easeInElastic:function(b,a,i,e,d){var f=0,h=e;if(a==0)return i;if((a/=d)==1)return i+e;f||(f=d*0.3);if(h<Math.abs(e)){h=e;b=f/4}else b=f/(2*Math.PI)*Math.asin(e/h);return-(h*Math.pow(2,10*(a-=1))*Math.sin((a*d-b)*2*Math.PI/f))+i},easeOutElastic:function(b,
a,i,e,d){var f=0,h=e;if(a==0)return i;if((a/=d)==1)return i+e;f||(f=d*0.3);if(h<Math.abs(e)){h=e;b=f/4}else b=f/(2*Math.PI)*Math.asin(e/h);return h*Math.pow(2,-10*a)*Math.sin((a*d-b)*2*Math.PI/f)+e+i},easeInOutElastic:function(b,a,i,e,d){var f=0,h=e;if(a==0)return i;if((a/=d/2)==2)return i+e;f||(f=d*0.3*1.5);if(h<Math.abs(e)){h=e;b=f/4}else b=f/(2*Math.PI)*Math.asin(e/h);if(a<1)return-0.5*h*Math.pow(2,10*(a-=1))*Math.sin((a*d-b)*2*Math.PI/f)+i;return h*Math.pow(2,-10*(a-=1))*Math.sin((a*d-b)*2*Math.PI/
f)*0.5+e+i},easeInBack:function(b,a,i,e,d,f){if(f==undefined)f=1.70158;return e*(a/=d)*a*((f+1)*a-f)+i},easeOutBack:function(b,a,i,e,d,f){if(f==undefined)f=1.70158;return e*((a=a/d-1)*a*((f+1)*a+f)+1)+i},easeInOutBack:function(b,a,i,e,d,f){if(f==undefined)f=1.70158;if((a/=d/2)<1)return e/2*a*a*(((f*=1.525)+1)*a-f)+i;return e/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+i},easeInBounce:function(b,a,i,e,d){return e-jQuery.easing.easeOutBounce(b,d-a,0,e,d)+i},easeOutBounce:function(b,a,i,e,d){return(a/=d)<1/
2.75?e*7.5625*a*a+i:a<2/2.75?e*(7.5625*(a-=1.5/2.75)*a+0.75)+i:a<2.5/2.75?e*(7.5625*(a-=2.25/2.75)*a+0.9375)+i:e*(7.5625*(a-=2.625/2.75)*a+0.984375)+i},easeInOutBounce:function(b,a,i,e,d){if(a<d/2)return jQuery.easing.easeInBounce(b,a*2,0,e,d)*0.5+i;return jQuery.easing.easeOutBounce(b,a*2-d,0,e,d)*0.5+e*0.5+i}});
(function(b,a,i,e){var d=b(a);b.fn.lazyload=function(f){function h(){var p=0;o.each(function(){var q=b(this);if(!m.skip_invisible||q.is(":visible"))if(!(b.abovethetop(this,m)||b.leftofbegin(this,m)))if(b.belowthefold(this,m)||b.rightoffold(this,m)){if(++p>m.failure_limit)return false}else{q.trigger("appear");p=0}})}var k,o=this,m={threshold:0,failure_limit:0,event:"scroll",effect:"show",container:a,data_attribute:"original",skip_invisible:false,appear:null,load:null,placeholder:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"};
return f&&(e!==f.failurelimit&&(f.failure_limit=f.failurelimit,delete f.failurelimit),e!==f.effectspeed&&(f.effect_speed=f.effectspeed,delete f.effectspeed),b.extend(m,f)),k=m.container===e||m.container===a?d:b(m.container),0===m.event.indexOf("scroll")&&k.bind(m.event,function(){return h()}),this.each(function(){var p=this,q=b(p);p.loaded=false;(q.attr("src")===e||q.attr("src")===false)&&q.is("img")&&q.attr("src",m.placeholder);q.one("appear",function(){if(!this.loaded){m.appear&&m.appear.call(p,
o.length,m);b("<img />").bind("load",function(){var n=q.attr("data-"+m.data_attribute);q.hide();q.is("img")?q.attr("src",n):q.css("background-image","url('"+n+"')");q[m.effect](m.effect_speed);p.loaded=true;n=b.grep(o,function(r){return!r.loaded});if(o=b(n),m.load)m.load.call(p,o.length,m)}).attr("src",q.attr("data-"+m.data_attribute))}});0!==m.event.indexOf("scroll")&&q.bind(m.event,function(){p.loaded||q.trigger("appear")})}),d.bind("resize",function(){h()}),/(?:iphone|ipod|ipad).*os 5/gi.test(navigator.appVersion)&&
d.bind("pageshow",function(p){p.originalEvent&&p.originalEvent.persisted&&o.each(function(){b(this).trigger("appear")})}),b(i).ready(function(){h()}),this};b.belowthefold=function(f,h){var k;return k=h.container===e||h.container===a?(a.innerHeight?a.innerHeight:d.height())+d.scrollTop():b(h.container).offset().top+b(h.container).height(),k<=b(f).offset().top-h.threshold};b.rightoffold=function(f,h){var k;return k=h.container===e||h.container===a?d.width()+d.scrollLeft():b(h.container).offset().left+
b(h.container).width(),k<=b(f).offset().left-h.threshold};b.abovethetop=function(f,h){var k;return k=h.container===e||h.container===a?d.scrollTop():b(h.container).offset().top,k>=b(f).offset().top+h.threshold+b(f).height()};b.leftofbegin=function(f,h){var k;return k=h.container===e||h.container===a?d.scrollLeft():b(h.container).offset().left,k>=b(f).offset().left+h.threshold+b(f).width()};b.inviewport=function(f,h){return!(b.rightoffold(f,h)||b.leftofbegin(f,h)||b.belowthefold(f,h)||b.abovethetop(f,
h))};b.extend(b.expr[":"],{"below-the-fold":function(f){return b.belowthefold(f,{threshold:0})},"above-the-top":function(f){return!b.belowthefold(f,{threshold:0})},"right-of-screen":function(f){return b.rightoffold(f,{threshold:0})},"left-of-screen":function(f){return!b.rightoffold(f,{threshold:0})},"in-viewport":function(f){return b.inviewport(f,{threshold:0})},"above-the-fold":function(f){return!b.belowthefold(f,{threshold:0})},"right-of-fold":function(f){return b.rightoffold(f,{threshold:0})},
"left-of-fold":function(f){return!b.rightoffold(f,{threshold:0})}})})(jQuery,window,document);(function(b){b(".img-lazy").lazyload({effect:"fadeIn",effectspeed:1E3,skip_invisible:false,threshold:200});b(".img-lazy-work").lazyload({effect:"fadeIn",effectspeed:1E3,skip_invisible:false,threshold:200})})(jQuery);
(function(b){"function"==typeof define&&define.amd?define(["jquery"],b):b(jQuery)})(function(b){function a(d,f,h){var k=f.hash.slice(1),o=document.getElementById(k)||document.getElementsByName(k)[0];if(o){d&&d.preventDefault();var m=b(h.target);if(!(h.lock&&m.is(":animated")||h.onBefore&&false===h.onBefore(d,o,m))){if(h.stop&&m.stop(true),h.hash){d=o.id===k?"id":"name";var p=b("<a> </a>").attr(d,k).css({position:"absolute",top:b(window).scrollTop(),left:b(window).scrollLeft()});o[d]="";b("body").prepend(p);
location.hash=f.hash;p.remove();o[d]=k}m.scrollTo(o,h).trigger("notify.serialScroll",[o])}}}var i=location.href.replace(/#.*/,""),e=b.localScroll=function(d){b("body").localScroll(d)};return e.defaults={duration:1E3,axis:"y",event:"click",stop:true,target:window,autoscroll:true},b.fn.localScroll=function(d){function f(){return!!this.href&&!!this.hash&&this.href.replace(this.hash,"")===i&&(!d.filter||b(this).is(d.filter))}return(d=b.extend({},e.defaults,d)).autoscroll&&d.hash&&location.hash&&(d.target&&
window.scrollTo(0,0),a(0,location,d)),d.lazy?this.on(d.event,"a,area",function(h){f.call(this)&&a(h,this,d)}):this.find("a,area").filter(f).bind(d.event,function(h){a(h,this,d)}).end().end()},e.hash=function(){},e});
(function(b){var a=b(window),i=a.height();a.resize(function(){i=a.height()});b.fn.parallax=function(e,d,f){function h(){var p=a.scrollTop();k.each(function(){var q=b(this),n=q.offset().top;q=o(q);n+q<p||n>p+i||k.css("backgroundPosition",e+" "+Math.round((m-p)*d)+"px")})}var k=b(this),o,m;k.each(function(){m=k.offset().top});o=f?function(p){return p.outerHeight(true)}:function(p){return p.height()};if(arguments.length<1||e===null)e="50%";if(arguments.length<2||d===null)d=0.1;if(arguments.length<3||
f===null)f=true;a.bind("scroll",h).resize(h);h()}})(jQuery);
(function(b){"function"==typeof define&&define.amd?define(["jquery"],b):b("object"==typeof exports?require("jquery"):window.jQuery||window.Zepto)})(function(b){var a,i,e,d,f,h,k=function(){},o=!!window.jQuery,m=b(window),p=function(c,g){a.ev.on("mfp"+c+".mfp",g)},q=function(c,g,j,l){var t=document.createElement("div");return t.className="mfp-"+c,j&&(t.innerHTML=j),l?g&&g.appendChild(t):(t=b(t),g&&t.appendTo(g)),t},n=function(c,g){a.ev.triggerHandler("mfp"+c,g);a.st.callbacks&&(c=c.charAt(0).toLowerCase()+
c.slice(1),a.st.callbacks[c]&&a.st.callbacks[c].apply(a,b.isArray(g)?g:[g]))},r=function(c){return c===h&&a.currTemplate.closeBtn||(a.currTemplate.closeBtn=b(a.st.closeMarkup.replace("%title%",a.st.tClose)),h=c),a.currTemplate.closeBtn},v=function(){b.magnificPopup.instance||(a=new k,a.init(),b.magnificPopup.instance=a)},s=function(){var c=document.createElement("p").style,g=["ms","O","Moz","Webkit"];if(void 0!==c.transition)return true;for(;g.length;)if(g.pop()+"Transition"in c)return true;return false};
k.prototype={constructor:k,init:function(){var c=navigator.appVersion;a.isIE7=-1!==c.indexOf("MSIE 7.");a.isIE8=-1!==c.indexOf("MSIE 8.");a.isLowIE=a.isIE7||a.isIE8;a.isAndroid=/android/gi.test(c);a.isIOS=/iphone|ipad|ipod/gi.test(c);a.supportsTransition=s();a.probablyMobile=a.isAndroid||a.isIOS||/(Opera Mini)|Kindle|webOS|BlackBerry|(Opera Mobi)|(Windows Phone)|IEMobile/i.test(navigator.userAgent);e=b(document);a.popupsCache={}},open:function(c){var g;if(c.isObj===false){a.items=c.items.toArray();
a.index=0;var j,l=c.items;for(g=0;g<l.length;g++)if(j=l[g],j.parsed&&(j=j.el[0]),j===c.el[0]){a.index=g;break}}else{a.items=b.isArray(c.items)?c.items:[c.items];a.index=c.index||0}if(a.isOpen)return void a.updateItemHTML();a.types=[];f="";a.ev=c.mainEl&&c.mainEl.length?c.mainEl.eq(0):e;c.key?(a.popupsCache[c.key]||(a.popupsCache[c.key]={}),a.currTemplate=a.popupsCache[c.key]):a.currTemplate={};a.st=b.extend(true,{},b.magnificPopup.defaults,c);a.fixedContentPos="auto"===a.st.fixedContentPos?!a.probablyMobile:
a.st.fixedContentPos;a.st.modal&&(a.st.closeOnContentClick=false,a.st.closeOnBgClick=false,a.st.showCloseBtn=false,a.st.enableEscapeKey=false);a.bgOverlay||(a.bgOverlay=q("bg").on("click.mfp",function(){a.close()}),a.wrap=q("wrap").attr("tabindex",-1).on("click.mfp",function(t){a._checkIfClose(t.target)&&a.close()}),a.container=q("container",a.wrap));a.contentContainer=q("content");a.st.preloader&&(a.preloader=q("preloader",a.container,a.st.tLoading));j=b.magnificPopup.modules;for(g=0;g<j.length;g++){l=
j[g];l=l.charAt(0).toUpperCase()+l.slice(1);a["init"+l].call(a)}n("BeforeOpen");a.st.showCloseBtn&&(a.st.closeBtnInside?(p("MarkupParse",function(t,w,x,y){x.close_replaceWith=r(y.type)}),f+=" mfp-close-btn-in"):a.wrap.append(r()));a.st.alignTop&&(f+=" mfp-align-top");a.wrap.css(a.fixedContentPos?{overflow:a.st.overflowY,overflowX:"hidden",overflowY:a.st.overflowY}:{top:m.scrollTop(),position:"absolute"});(a.st.fixedBgPos===false||"auto"===a.st.fixedBgPos&&!a.fixedContentPos)&&a.bgOverlay.css({height:e.height(),
position:"absolute"});a.st.enableEscapeKey&&e.on("keyup.mfp",function(t){27===t.keyCode&&a.close()});m.on("resize.mfp",function(){a.updateSize()});a.st.closeOnContentClick||(f+=" mfp-auto-cursor");f&&a.wrap.addClass(f);g=a.wH=m.height();j={};if(a.fixedContentPos&&a._hasScrollBar(g))(l=a._getScrollbarSize())&&(j.marginRight=l);a.fixedContentPos&&(a.isIE7?b("body, html").css("overflow","hidden"):j.overflow="hidden");l=a.st.mainClass;return a.isIE7&&(l+=" mfp-ie7"),l&&a._addClassToMFP(l),a.updateItemHTML(),
n("BuildControls"),b("html").css(j),a.bgOverlay.add(a.wrap).prependTo(a.st.prependTo||b(document.body)),a._lastFocusedEl=document.activeElement,setTimeout(function(){a.content?(a._addClassToMFP("mfp-ready"),a._setFocus()):a.bgOverlay.addClass("mfp-ready");e.on("focusin.mfp",a._onFocusIn)},16),a.isOpen=true,a.updateSize(g),n("Open"),c},close:function(){a.isOpen&&(n("BeforeClose"),a.isOpen=false,a.st.removalDelay&&!a.isLowIE&&a.supportsTransition?(a._addClassToMFP("mfp-removing"),setTimeout(function(){a._close()},
a.st.removalDelay)):a._close())},_close:function(){n("Close");var c="mfp-removing mfp-ready ";if(a.bgOverlay.detach(),a.wrap.detach(),a.container.empty(),a.st.mainClass&&(c+=a.st.mainClass+" "),a._removeClassFromMFP(c),a.fixedContentPos){c={marginRight:""};a.isIE7?b("body, html").css("overflow",""):c.overflow="";b("html").css(c)}e.off("keyup.mfp focusin.mfp");a.ev.off(".mfp");a.wrap.attr("class","mfp-wrap").removeAttr("style");a.bgOverlay.attr("class","mfp-bg");a.container.attr("class","mfp-container");
!a.st.showCloseBtn||a.st.closeBtnInside&&a.currTemplate[a.currItem.type]!==true||a.currTemplate.closeBtn&&a.currTemplate.closeBtn.detach();a._lastFocusedEl&&b(a._lastFocusedEl).focus();a.currItem=null;a.content=null;a.currTemplate=null;a.prevHeight=0;n("AfterClose")},updateSize:function(c){if(a.isIOS){c=window.innerHeight*(document.documentElement.clientWidth/window.innerWidth);a.wrap.css("height",c);a.wH=c}else a.wH=c||m.height();a.fixedContentPos||a.wrap.css("height",a.wH);n("Resize")},updateItemHTML:function(){var c=
a.items[a.index];a.contentContainer.detach();a.content&&a.content.detach();c.parsed||(c=a.parseEl(a.index));var g=c.type;if(n("BeforeChange",[a.currItem?a.currItem.type:"",g]),a.currItem=c,!a.currTemplate[g]){var j=a.st[g]?a.st[g].markup:false;n("FirstMarkupParse",j);a.currTemplate[g]=j?b(j):true}d&&d!==c.type&&a.container.removeClass("mfp-"+d+"-holder");j=a["get"+g.charAt(0).toUpperCase()+g.slice(1)](c,a.currTemplate[g]);a.appendContent(j,g);c.preloaded=true;n("Change",c);d=c.type;a.container.prepend(a.contentContainer);
n("AfterChange")},appendContent:function(c,g){(a.content=c)?a.st.showCloseBtn&&a.st.closeBtnInside&&a.currTemplate[g]===true?a.content.find(".mfp-close").length||a.content.append(r()):a.content=c:a.content="";n("BeforeAppend");a.container.addClass("mfp-"+g+"-holder");a.contentContainer.append(a.content)},parseEl:function(c){var g,j=a.items[c];if(j.tagName?j={el:b(j)}:(g=j.type,j={data:j,src:j.src}),j.el){for(var l=a.types,t=0;t<l.length;t++)if(j.el.hasClass("mfp-"+l[t])){g=l[t];break}j.src=j.el.attr("data-mfp-src");
j.src||(j.src=j.el.attr("href"))}return j.type=g||a.st.type||"inline",j.index=c,j.parsed=true,a.items[c]=j,n("ElementParse",j),a.items[c]},addGroup:function(c,g){var j=function(l){l.mfpEl=this;a._openClick(l,c,g)};g||(g={});g.mainEl=c;g.items?(g.isObj=true,c.off("click.magnificPopup").on("click.magnificPopup",j)):(g.isObj=false,g.delegate?c.off("click.magnificPopup").on("click.magnificPopup",g.delegate,j):(g.items=c,c.off("click.magnificPopup").on("click.magnificPopup",j)))},_openClick:function(c,
g,j){if((void 0!==j.midClick?j.midClick:b.magnificPopup.defaults.midClick)||2!==c.which&&!c.ctrlKey&&!c.metaKey){var l=void 0!==j.disableOn?j.disableOn:b.magnificPopup.defaults.disableOn;if(l)if(b.isFunction(l)){if(!l.call(a))return true}else if(m.width()<l)return true;c.type&&(c.preventDefault(),a.isOpen&&c.stopPropagation());j.el=b(c.mfpEl);j.delegate&&(j.items=g.find(j.delegate));a.open(j)}},updateStatus:function(c,g){if(a.preloader){i!==c&&a.container.removeClass("mfp-s-"+i);g||"loading"!==c||
(g=a.st.tLoading);var j={status:c,text:g};n("UpdateStatus",j);c=j.status;g=j.text;a.preloader.html(g);a.preloader.find("a").on("click",function(l){l.stopImmediatePropagation()});a.container.addClass("mfp-s-"+c);i=c}},_checkIfClose:function(c){if(!b(c).hasClass("mfp-prevent-close")){var g=a.st.closeOnContentClick,j=a.st.closeOnBgClick;if(g&&j)return true;if(!a.content||b(c).hasClass("mfp-close")||a.preloader&&c===a.preloader[0])return true;if(c===a.content[0]||b.contains(a.content[0],c)){if(g)return true}else if(j&&
b.contains(document,c))return true;return false}},_addClassToMFP:function(c){a.bgOverlay.addClass(c);a.wrap.addClass(c)},_removeClassFromMFP:function(c){this.bgOverlay.removeClass(c);a.wrap.removeClass(c)},_hasScrollBar:function(c){return(a.isIE7?e.height():document.body.scrollHeight)>(c||m.height())},_setFocus:function(){(a.st.focus?a.content.find(a.st.focus).eq(0):a.wrap).focus()},_onFocusIn:function(c){return c.target===a.wrap[0]||b.contains(a.wrap[0],c.target)?void 0:(a._setFocus(),false)},_parseMarkup:function(c,
g,j){var l;j.data&&(g=b.extend(j.data,g));n("MarkupParse",[c,g,j]);b.each(g,function(t,w){if(void 0===w||w===false)return true;if(l=t.split("_"),l.length>1){var x=c.find(".mfp-"+l[0]);if(x.length>0){var y=l[1];"replaceWith"===y?x[0]!==w[0]&&x.replaceWith(w):"img"===y?x.is("img")?x.attr("src",w):x.replaceWith('<img src="'+w+'" class="'+x.attr("class")+'" />'):x.attr(l[1],w)}}else c.find(".mfp-"+t).html(w)})},_getScrollbarSize:function(){if(void 0===a.scrollbarSize){var c=document.createElement("div");
c.style.cssText="width: 99px; height: 99px; overflow: scroll; position: absolute; top: -9999px;";document.body.appendChild(c);a.scrollbarSize=c.offsetWidth-c.clientWidth;document.body.removeChild(c)}return a.scrollbarSize}};b.magnificPopup={instance:null,proto:k.prototype,modules:[],open:function(c,g){return v(),c=c?b.extend(true,{},c):{},c.isObj=true,c.index=g||0,this.instance.open(c)},close:function(){return b.magnificPopup.instance&&b.magnificPopup.instance.close()},registerModule:function(c,g){g.options&&
(b.magnificPopup.defaults[c]=g.options);b.extend(this.proto,g.proto);this.modules.push(c)},defaults:{disableOn:0,key:null,midClick:false,mainClass:"",preloader:true,focus:"",closeOnContentClick:false,closeOnBgClick:true,closeBtnInside:true,showCloseBtn:true,enableEscapeKey:true,modal:false,alignTop:false,removalDelay:0,prependTo:null,fixedContentPos:"auto",fixedBgPos:"auto",overflowY:"auto",closeMarkup:'<button title="%title%" type="button" class="mfp-close">×</button>',tClose:"Close (Esc)",
tLoading:"Loading..."}};b.fn.magnificPopup=function(c){v();var g=b(this);if("string"==typeof c)if("open"===c){var j,l=o?g.data("magnificPopup"):g[0].magnificPopup,t=parseInt(arguments[1],10)||0;l.items?j=l.items[t]:(j=g,l.delegate&&(j=j.find(l.delegate)),j=j.eq(t));a._openClick({mfpEl:j},g,l)}else a.isOpen&&a[c].apply(a,Array.prototype.slice.call(arguments,1));else{c=b.extend(true,{},c);o?g.data("magnificPopup",c):g[0].magnificPopup=c;a.addGroup(g,c)}return g};var u,z,B,C=function(){B&&(z.after(B.addClass(u)).detach(),
B=null)};b.magnificPopup.registerModule("inline",{options:{hiddenClass:"hide",markup:"",tNotFound:"Content not found"},proto:{initInline:function(){a.types.push("inline");p("Close.inline",function(){C()})},getInline:function(c,g){if(C(),c.src){var j=a.st.inline,l=b(c.src);if(l.length){var t=l[0].parentNode;t&&t.tagName&&(z||(u=j.hiddenClass,z=q(u),u="mfp-"+u),B=l.after(z).detach().removeClass(u));a.updateStatus("ready")}else{a.updateStatus("error",j.tNotFound);l=b("<div>")}return c.inlineElement=
l,l}return a.updateStatus("ready"),a._parseMarkup(g,{},c),g}}});var A,G=function(){A&&b(document.body).removeClass(A)},H=function(){G();a.req&&a.req.abort()};b.magnificPopup.registerModule("ajax",{options:{settings:null,cursor:"mfp-ajax-cur",tError:'<a href="%url%">The content</a> could not be loaded.'},proto:{initAjax:function(){a.types.push("ajax");A=a.st.ajax.cursor;p("Close.ajax",H);p("BeforeChange.ajax",H)},getAjax:function(c){A&&b(document.body).addClass(A);a.updateStatus("loading");var g=b.extend({url:c.src,
success:function(j,l,t){j={data:j,xhr:t};n("ParseAjax",j);a.appendContent(b(j.data),"ajax");c.finished=true;G();a._setFocus();setTimeout(function(){a.wrap.addClass("mfp-ready")},16);a.updateStatus("ready");n("AjaxContentAdded")},error:function(){G();c.finished=c.loadError=true;a.updateStatus("error",a.st.ajax.tError.replace("%url%",c.src))}},a.st.ajax.settings);return a.req=b.ajax(g),""}}});var E,P=function(c){if(c.data&&void 0!==c.data.title)return c.data.title;var g=a.st.image.titleSrc;if(g){if(b.isFunction(g))return g.call(a,
c);if(c.el)return c.el.attr(g)||""}return""};b.magnificPopup.registerModule("image",{options:{markup:'<div class="mfp-figure"><div class="mfp-close"></div><figure><div class="mfp-img"></div><figcaption><div class="mfp-bottom-bar"><div class="mfp-title"></div><div class="mfp-counter"></div></div></figcaption></figure></div>',cursor:"mfp-zoom-out-cur",titleSrc:"title",verticalFit:true,tError:'<a href="%url%">The image</a> could not be loaded.'},proto:{initImage:function(){var c=a.st.image;a.types.push("image");
p("Open.image",function(){"image"===a.currItem.type&&c.cursor&&b(document.body).addClass(c.cursor)});p("Close.image",function(){c.cursor&&b(document.body).removeClass(c.cursor);m.off("resize.mfp")});p("Resize.image",a.resizeImage);a.isLowIE&&p("AfterChange",a.resizeImage)},resizeImage:function(){var c=a.currItem;if(c&&c.img&&a.st.image.verticalFit){var g=0;a.isLowIE&&(g=parseInt(c.img.css("padding-top"),10)+parseInt(c.img.css("padding-bottom"),10));c.img.css("max-height",a.wH-g)}},_onImageHasSize:function(c){c.img&&
(c.hasSize=true,E&&clearInterval(E),c.isCheckingImgSize=false,n("ImageHasSize",c),c.imgHidden&&(a.content&&a.content.removeClass("mfp-loading"),c.imgHidden=false))},findImageSize:function(c){var g=0,j=c.img[0],l=function(t){E&&clearInterval(E);E=setInterval(function(){return j.naturalWidth>0?void a._onImageHasSize(c):(g>200&&clearInterval(E),g++,void(3===g?l(10):40===g?l(50):100===g&&l(500)))},t)};l(1)},getImage:function(c,g){var j=0,l=function(){c&&(c.img[0].complete?(c.img.off(".mfploader"),c===
a.currItem&&(a._onImageHasSize(c),a.updateStatus("ready")),c.hasSize=true,c.loaded=true,n("ImageLoadComplete")):(j++,200>j?setTimeout(l,100):t()))},t=function(){c&&(c.img.off(".mfploader"),c===a.currItem&&(a._onImageHasSize(c),a.updateStatus("error",w.tError.replace("%url%",c.src))),c.hasSize=true,c.loaded=true,c.loadError=true)},w=a.st.image,x=g.find(".mfp-img");if(x.length){var y=document.createElement("img");y.className="mfp-img";c.el&&c.el.find("img").length&&(y.alt=c.el.find("img").attr("alt"));
c.img=b(y).on("load.mfploader",l).on("error.mfploader",t);y.src=c.src;x.is("img")&&(c.img=c.img.clone());y=c.img[0];y.naturalWidth>0?c.hasSize=true:y.width||(c.hasSize=false)}return a._parseMarkup(g,{title:P(c),img_replaceWith:c.img},c),a.resizeImage(),c.hasSize?(E&&clearInterval(E),c.loadError?(g.addClass("mfp-loading"),a.updateStatus("error",w.tError.replace("%url%",c.src))):(g.removeClass("mfp-loading"),a.updateStatus("ready")),g):(a.updateStatus("loading"),c.loading=true,c.hasSize||(c.imgHidden=
true,g.addClass("mfp-loading"),a.findImageSize(c)),g)}}});var J;b.magnificPopup.registerModule("zoom",{options:{enabled:false,easing:"ease-in-out",duration:300,opener:function(c){return c.is("img")?c:c.find("img")}},proto:{initZoom:function(){var c,g=a.st.zoom;if(g.enabled&&a.supportsTransition){var j,l,t=g.duration,w=function(y){y=y.clone().removeAttr("style").removeAttr("class").addClass("mfp-animated-image");var F={position:"fixed",zIndex:9999,left:0,top:0,"-webkit-backface-visibility":"hidden"};
return F["-webkit-transition"]=F["-moz-transition"]=F["-o-transition"]=F.transition="all "+g.duration/1E3+"s "+g.easing,y.css(F),y},x=function(){a.content.css("visibility","visible")};p("BuildControls.zoom",function(){if(a._allowZoom()){if(clearTimeout(j),a.content.css("visibility","hidden"),c=a._getItemToZoom(),!c)return void x();l=w(c);l.css(a._getOffset());a.wrap.append(l);j=setTimeout(function(){l.css(a._getOffset(true));j=setTimeout(function(){x();setTimeout(function(){l.remove();c=l=null;n("ZoomAnimationEnded")},
16)},t)},16)}});p("BeforeClose.zoom",function(){if(a._allowZoom()){if(clearTimeout(j),a.st.removalDelay=t,!c){if(c=a._getItemToZoom(),!c)return;l=w(c)}l.css(a._getOffset(true));a.wrap.append(l);a.content.css("visibility","hidden");setTimeout(function(){l.css(a._getOffset())},16)}});p("Close.zoom",function(){a._allowZoom()&&(x(),l&&l.remove(),c=null)})}},_allowZoom:function(){return"image"===a.currItem.type},_getItemToZoom:function(){return a.currItem.hasSize?a.currItem.img:false},_getOffset:function(c){var g;
g=c?a.currItem.img:a.st.zoom.opener(a.currItem.el||a.currItem);c=g.offset();var j=parseInt(g.css("padding-top"),10),l=parseInt(g.css("padding-bottom"),10);c.top-=b(window).scrollTop()-j;g={width:g.width(),height:(o?g.innerHeight():g[0].offsetHeight)-l-j};return(void 0===J&&(J=void 0!==document.createElement("p").style.MozTransform),J)?g["-moz-transform"]=g.transform="translate("+c.left+"px,"+c.top+"px)":(g.left=c.left,g.top=c.top),g}}});var K=function(c){if(a.currTemplate.iframe){var g=a.currTemplate.iframe.find("iframe");
g.length&&(c||(g[0].src="//about:blank"),a.isIE8&&g.css("display",c?"block":"none"))}};b.magnificPopup.registerModule("iframe",{options:{markup:'<div class="mfp-iframe-scaler"><div class="mfp-close"></div><iframe class="mfp-iframe" src="//about:blank" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>',srcAction:"iframe_src",patterns:{youtube:{index:"youtube.com",id:"v=",src:"https://www.youtube.com/embed/%id%?autoplay=1"},
vimeo:{index:"vimeo.com/",id:"/",src:"//player.vimeo.com/video/%id%?autoplay=1"},gmaps:{index:"//maps.google.",src:"%id%&output=embed"}}},proto:{initIframe:function(){a.types.push("iframe");p("BeforeChange",function(c,g,j){g!==j&&(g==="iframe"?K():j==="iframe"&&K(true))});p("Close.iframe",function(){K()})},getIframe:function(c,g){var j=c.src,l=a.st.iframe;b.each(l.patterns,function(){return j.indexOf(this.index)>-1?(this.id&&(j="string"==typeof this.id?j.substr(j.lastIndexOf(this.id)+this.id.length,
j.length):this.id.call(this,j)),j=this.src.replace("%id%",j),false):void 0});var t={};return l.srcAction&&(t[l.srcAction]=j),a._parseMarkup(g,t,c),a.updateStatus("ready"),g}}});var L=function(c){var g=a.items.length;return c>g-1?c-g:0>c?g+c:c};b.magnificPopup.registerModule("gallery",{options:{enabled:false,arrowMarkup:'<button title="%title%" type="button" class="mfp-arrow mfp-arrow-%dir%"></button>',preload:[0,2],navigateByImgClick:true,arrows:true,tPrev:"Previous (Left arrow key)",tNext:"Next (Right arrow key)",
tCounter:"%curr% of %total%"},proto:{initGallery:function(){var c=a.st.gallery,g=Boolean(b.fn.mfpFastClick);return a.direction=true,c&&c.enabled?(f+=" mfp-gallery",p("Open.mfp-gallery",function(){c.navigateByImgClick&&a.wrap.on("click.mfp-gallery",".mfp-img",function(){return a.items.length>1?(a.next(),false):void 0});e.on("keydown.mfp-gallery",function(j){37===j.keyCode?a.prev():39===j.keyCode&&a.next()})}),p("UpdateStatus.mfp-gallery",function(j,l){l.text&&(l.text=l.text.replace(/%curr%/gi,a.currItem.index+
1).replace(/%total%/gi,a.items.length))}),p("MarkupParse.mfp-gallery",function(j,l,t,w){j=a.items.length;t.counter=j>1?c.tCounter.replace(/%curr%/gi,w.index+1).replace(/%total%/gi,j):""}),p("BuildControls.mfp-gallery",function(){if(a.items.length>1&&c.arrows&&!a.arrowLeft){var j=c.arrowMarkup,l=a.arrowLeft=b(j.replace(/%title%/gi,c.tPrev).replace(/%dir%/gi,"left")).addClass("mfp-prevent-close");j=a.arrowRight=b(j.replace(/%title%/gi,c.tNext).replace(/%dir%/gi,"right")).addClass("mfp-prevent-close");
var t=g?"mfpFastClick":"click";l[t](function(){a.prev()});j[t](function(){a.next()});a.isIE7&&(q("b",l[0],false,true),q("a",l[0],false,true),q("b",j[0],false,true),q("a",j[0],false,true));a.container.append(l.add(j))}}),p("Change.mfp-gallery",function(){a._preloadTimeout&&clearTimeout(a._preloadTimeout);a._preloadTimeout=setTimeout(function(){a.preloadNearbyImages();a._preloadTimeout=null},16)}),void p("Close.mfp-gallery",function(){e.off(".mfp-gallery");a.wrap.off("click.mfp-gallery");a.arrowLeft&&
g&&a.arrowLeft.add(a.arrowRight).destroyMfpFastClick();a.arrowRight=a.arrowLeft=null})):false},next:function(){a.direction=true;a.index=L(a.index+1);a.updateItemHTML()},prev:function(){a.direction=false;a.index=L(a.index-1);a.updateItemHTML()},goTo:function(c){a.direction=c>=a.index;a.index=c;a.updateItemHTML()},preloadNearbyImages:function(){var c;c=a.st.gallery.preload;var g=Math.min(c[0],a.items.length),j=Math.min(c[1],a.items.length);for(c=1;c<=(a.direction?j:g);c++)a._preloadItem(a.index+c);
for(c=1;c<=(a.direction?g:j);c++)a._preloadItem(a.index-c)},_preloadItem:function(c){if(c=L(c),!a.items[c].preloaded){var g=a.items[c];g.parsed||(g=a.parseEl(c));n("LazyLoad",g);"image"===g.type&&(g.img=b('<img class="mfp-img" />').on("load.mfploader",function(){g.hasSize=true}).on("error.mfploader",function(){g.hasSize=true;g.loadError=true;n("LazyLoadError",g)}).attr("src",g.src));g.preloaded=true}}}});b.magnificPopup.registerModule("retina",{options:{replaceSrc:function(c){return c.src.replace(/\.\w+$/,
function(g){return"@2x"+g})},ratio:1},proto:{initRetina:function(){if(window.devicePixelRatio>1){var c=a.st.retina,g=c.ratio;g=isNaN(g)?g():g;g>1&&(p("ImageHasSize.retina",function(j,l){l.img.css({"max-width":l.img[0].naturalWidth/g,width:"100%"})}),p("ElementParse.retina",function(j,l){l.src=c.replaceSrc(l,g)}))}}}});(function(){var c="ontouchstart"in window,g=function(){m.off("touchmove"+j+" touchend"+j)},j=".mfpFastClick";b.fn.mfpFastClick=function(l){return b(this).each(function(){var t,w=b(this);
if(c){var x,y,F,M,D,N;w.on("touchstart"+j,function(O){M=false;N=1;D=O.originalEvent?O.originalEvent.touches[0]:O.touches[0];y=D.clientX;F=D.clientY;m.on("touchmove"+j,function(I){D=I.originalEvent?I.originalEvent.touches:I.touches;N=D.length;D=D[0];(Math.abs(D.clientX-y)>10||Math.abs(D.clientY-F)>10)&&(M=true,g())}).on("touchend"+j,function(I){g();M||N>1||(t=true,I.preventDefault(),clearTimeout(x),x=setTimeout(function(){t=false},1E3),l())})})}w.on("click"+j,function(){t||l()})})};b.fn.destroyMfpFastClick=
function(){b(this).off("touchstart"+j+" click"+j);c&&m.off("touchmove"+j+" touchend"+j)}})();v()});
(function(b){"function"===typeof define&&define.amd?define(["jquery"],b):"undefined"!==typeof module&&module.exports?module.exports=b(require("jquery")):b(jQuery)})(function(b){function a(d){return!d.nodeName||-1!==b.inArray(d.nodeName.toLowerCase(),["iframe","#document","html","body"])}function i(d){return b.isFunction(d)||b.isPlainObject(d)?d:{top:d,left:d}}var e=b.scrollTo=function(d,f,h){return b(window).scrollTo(d,f,h)};e.defaults={axis:"xy",duration:0,limit:true};b.fn.scrollTo=function(d,f,
h){"object"===typeof f&&(h=f,f=0);"function"===typeof h&&(h={onAfter:h});"max"===d&&(d=9E9);h=b.extend({},e.defaults,h);f=f||h.duration;var k=h.queue&&1<h.axis.length;k&&(f/=2);h.offset=i(h.offset);h.over=i(h.over);return this.each(function(){function o(u){var z=b.extend({},h,{queue:true,duration:f,complete:u&&function(){u.call(p,n,h)}});q.animate(r,z)}if(null!==d){var m=a(this),p=m?this.contentWindow||window:this,q=b(p),n=d,r={},v;switch(typeof n){case "number":case "string":if(/^([+-]=?)?\d+(\.\d+)?(px|%)?$/.test(n)){n=
i(n);break}n=m?b(n):b(n,p);case "object":if(n.length===0)return;if(n.is||n.style)v=(n=b(n)).offset()}var s=b.isFunction(h.offset)&&h.offset(p,n)||h.offset;b.each(h.axis.split(""),function(u,z){var B="x"===z?"Left":"Top",C=B.toLowerCase(),A="scroll"+B,G=q[A](),H=e.max(p,z);v?(r[A]=v[C]+(m?0:G-q.offset()[C]),h.margin&&(r[A]-=parseInt(n.css("margin"+B),10)||0,r[A]-=parseInt(n.css("border"+B+"Width"),10)||0),r[A]+=s[C]||0,h.over[C]&&(r[A]+=n["x"===z?"width":"height"]()*h.over[C])):(B=n[C],r[A]=B.slice&&
"%"===B.slice(-1)?parseFloat(B)/100*H:B);h.limit&&/^\d+$/.test(r[A])&&(r[A]=0>=r[A]?0:Math.min(r[A],H));!u&&1<h.axis.length&&(G===r[A]?r={}:k&&(o(h.onAfterFirst),r={}))});o(h.onAfter)}})};e.max=function(d,f){var h="x"===f?"Width":"Height",k="scroll"+h;if(!a(d))return d[k]-b(d)[h.toLowerCase()]();h="client"+h;var o=d.ownerDocument||d.document,m=o.documentElement;o=o.body;return Math.max(m[k],o[k])-Math.min(m[h],o[h])};b.Tween.propHooks.scrollLeft=b.Tween.propHooks.scrollTop={get:function(d){return b(d.elem)[d.prop]()},
set:function(d){var f=this.get(d);if(d.options.interrupt&&d._last&&d._last!==f)return b(d.elem).stop();var h=Math.round(d.now);f!==h&&(b(d.elem)[d.prop](h),d._last=this.get(d))}};return e});(function(b){b(document).ready(function(){var a=b(".text-rotate"),i=a.html();a.attr("aria-hidden","true");a.before("<span class='sr-only'>"+i+"</span>");a.textrotator({animation:"dissolve",separator:",",speed:4E3})})})(jQuery);
(function(b){var a={animation:"dissolve",separator:",",speed:2E3};b.fn.textrotator=function(i){var e=b.extend({},a,i);return this.each(function(){var d=b(this),f=[];b.each(d.text().split(e.separator),function(h,k){f.push(k)});d.text(f[0]);setInterval(function(){switch(e.animation){case "dissolve":d.animate({textShadowBlur:20,opacity:0},500,function(){k=b.inArray(d.text(),f);if(k+1==f.length)k=-1;d.text(f[k+1]).animate({textShadowBlur:0,opacity:1},500)});break;case "flip":d.find(".back").length>0&&
d.html(d.find(".back").html());var h=d.text(),k=b.inArray(h,f);if(k+1==f.length)k=-1;d.html("");b("<span class='front'>"+h+"</span>").appendTo(d);b("<span class='back'>"+f[k+1]+"</span>").appendTo(d);d.wrapInner("<span class='rotating' ></span>").find(".rotating").hide().addClass("flip").show().css({"-webkit-transform":" rotateY(-180deg)","-moz-transform":" rotateY(-180deg)","-o-transform":" rotateY(-180deg)",transform:" rotateY(-180deg)"});break;case "flipUp":d.find(".back").length>0&&d.html(d.find(".back").html());
h=d.text();k=b.inArray(h,f);if(k+1==f.length)k=-1;d.html("");b("<span class='front'>"+h+"</span>").appendTo(d);b("<span class='back'>"+f[k+1]+"</span>").appendTo(d);d.wrapInner("<span class='rotating' ></span>").find(".rotating").hide().addClass("flip up").show().css({"-webkit-transform":" rotateX(-180deg)","-moz-transform":" rotateX(-180deg)","-o-transform":" rotateX(-180deg)",transform:" rotateX(-180deg)"});break;case "flipCube":d.find(".back").length>0&&d.html(d.find(".back").html());h=d.text();k=b.inArray(h,
f);if(k+1==f.length)k=-1;d.html("");b("<span class='front'>"+h+"</span>").appendTo(d);b("<span class='back'>"+f[k+1]+"</span>").appendTo(d);d.wrapInner("<span class='rotating' ></span>").find(".rotating").hide().addClass("flip cube").show().css({"-webkit-transform":" rotateY(180deg)","-moz-transform":" rotateY(180deg)","-o-transform":" rotateY(180deg)",transform:" rotateY(180deg)"});break;case "flipCubeUp":d.find(".back").length>0&&d.html(d.find(".back").html());h=d.text();k=b.inArray(h,f);if(k+1==f.length)k=
-1;d.html("");b("<span class='front'>"+h+"</span>").appendTo(d);b("<span class='back'>"+f[k+1]+"</span>").appendTo(d);d.wrapInner("<span class='rotating' ></span>").find(".rotating").hide().addClass("flip cube up").show().css({"-webkit-transform":" rotateX(180deg)","-moz-transform":" rotateX(180deg)","-o-transform":" rotateX(180deg)",transform:" rotateX(180deg)"});break;case "spin":d.find(".rotating").length>0&&d.html(d.find(".rotating").html());k=b.inArray(d.text(),f);if(k+1==f.length)k=-1;d.wrapInner("<span class='rotating spin' ></span>").find(".rotating").hide().text(f[k+
1]).show().css({"-webkit-transform":" rotate(0) scale(1)","-moz-transform":"rotate(0) scale(1)","-o-transform":"rotate(0) scale(1)",transform:"rotate(0) scale(1)"});break;case "fade":d.fadeOut(e.speed,function(){k=b.inArray(d.text(),f);if(k+1==f.length)k=-1;d.text(f[k+1]).fadeIn(e.speed)})}},e.speed)})}})(window.jQuery);
(function(b){var a=Array.prototype.slice,i=Array.prototype.splice,e={topSpacing:0,bottomSpacing:0,className:"is-sticky",wrapperClassName:"sticky-wrapper",center:false,getWidthFrom:"",widthFromWrapper:true,responsiveWidth:false},d=b(window),f=b(document),h=[],k=d.height(),o=function(){var q=d.scrollTop(),n=f.height(),r=n-k;r=q>r?r-q:0;for(var v=0;v<h.length;v++){var s=h[v],u=s.stickyWrapper.offset().top-s.topSpacing-r;if(q<=u){if(s.currentTop!==null){s.stickyElement.css({width:"",position:"",top:""});
s.stickyElement.parent().removeClass(s.className);s.stickyElement.trigger("sticky-end",[s]);s.currentTop=null}}else{u=n-s.stickyElement.outerHeight()-s.topSpacing-s.bottomSpacing-q-r;if(u<0)u+=s.topSpacing;else u=s.topSpacing;if(s.currentTop!=u){var z;if(s.getWidthFrom)z=b(s.getWidthFrom).width()||null;else if(s.widthFromWrapper)z=s.stickyWrapper.width();if(z==null)z=s.stickyElement.width();s.stickyElement.css("width",z).css("position","fixed").css("top",u);s.stickyElement.parent().addClass(s.className);
s.currentTop===null?s.stickyElement.trigger("sticky-start",[s]):s.stickyElement.trigger("sticky-update",[s]);if(s.currentTop===s.topSpacing&&s.currentTop>u||s.currentTop===null&&u<s.topSpacing)s.stickyElement.trigger("sticky-bottom-reached",[s]);else s.currentTop!==null&&u===s.topSpacing&&s.currentTop<u&&s.stickyElement.trigger("sticky-bottom-unreached",[s]);s.currentTop=u}}}},m=function(){k=d.height();for(var q=0;q<h.length;q++){var n=h[q],r=null;if(n.getWidthFrom){if(n.responsiveWidth===true)r=
b(n.getWidthFrom).width()}else if(n.widthFromWrapper)r=n.stickyWrapper.width();r!=null&&n.stickyElement.css("width",r)}},p={init:function(q){var n=b.extend({},e,q);return this.each(function(){var r=b(this),v=r.attr("id"),s=r.outerHeight();v=v?v+"-"+e.wrapperClassName:e.wrapperClassName;v=b("<div></div>").attr("id",v).addClass(n.wrapperClassName);r.wrapAll(v);v=r.parent();n.center&&v.css({width:r.outerWidth(),marginLeft:"auto",marginRight:"auto"});r.css("float")=="right"&&r.css({"float":"none"}).parent().css({"float":"right"});
v.css("height",s);n.stickyElement=r;n.stickyWrapper=v;n.currentTop=null;h.push(n)})},update:o,unstick:function(){return this.each(function(){for(var q=b(this),n=-1,r=h.length;r-- >0;)if(h[r].stickyElement.get(0)===this){i.call(h,r,1);n=r}if(n!=-1){q.unwrap();q.css({width:"",position:"",top:"","float":""})}})}};if(window.addEventListener){window.addEventListener("scroll",o,false);window.addEventListener("resize",m,false)}else if(window.attachEvent){window.attachEvent("onscroll",o);window.attachEvent("onresize",
m)}b.fn.sticky=function(q){if(p[q])return p[q].apply(this,a.call(arguments,1));else if(typeof q==="object"||!q)return p.init.apply(this,arguments);else b.error("Method "+q+" does not exist on jQuery.sticky")};b.fn.unstick=function(q){if(p[q])return p[q].apply(this,a.call(arguments,1));else if(typeof q==="object"||!q)return p.unstick.apply(this,arguments);else b.error("Method "+q+" does not exist on jQuery.sticky")};b(function(){setTimeout(o,0)})})(jQuery);
(function(b){b.belowthefold=function(a,i){return b(window).height()+b(window).scrollTop()<=b(a).offset().top-i.threshold};b.abovethetop=function(a,i){return b(window).scrollTop()>=b(a).offset().top+b(a).height()-i.threshold};b.rightofscreen=function(a,i){return b(window).width()+b(window).scrollLeft()<=b(a).offset().left-i.threshold};b.leftofscreen=function(a,i){return b(window).scrollLeft()>=b(a).offset().left+b(a).width()-i.threshold};b.inviewport=function(a,i){return!b.rightofscreen(a,i)&&!b.leftofscreen(a,
i)&&!b.belowthefold(a,i)&&!b.abovethetop(a,i)};b.extend(b.expr[":"],{"below-the-fold":function(a){return b.belowthefold(a,{threshold:0})},"above-the-top":function(a){return b.abovethetop(a,{threshold:0})},"left-of-screen":function(a){return b.leftofscreen(a,{threshold:0})},"right-of-screen":function(a){return b.rightofscreen(a,{threshold:0})},"in-viewport":function(a){return b.inviewport(a,{threshold:0})}})})(jQuery);
